### ISSUE TITLE
how can compiling new files

### ISSUE THREAD

**Issue by jianle** [webpack/webpack-dev-server#1006]
#### Question:

I can compiling when files change, but can't compiling when new files. so, how can i do it ?

#### Please mention your webpack and Operating System version.
webpack: ^1.12.13
webpack-dev-server: ^1.14.1

**Comment by akatechis** [comment]
If you're referring to adding new files to a project in which webpack-dev-server is already running and watching the files, then merely adding the file to a directory will not work. You will have to also `require()` or `import()` that module from a module that is already being watched by webpack.

Example:
If my project has a main.js entrypoint
```javascript
var one = require("./one");
var two = require("./two");
```

If I create `three.js`, webpack will not know that it is part of the project, because the last time it walked the dependency graph, it didn't see it. If I update main.js and add `var three = require("./three");` then webpack will recompile main.js, analyze its dependencies again, notice that `three.js` is now a dependency and start looking at it.
