### ISSUE TITLE
Define method when defining context in proxy-config

### ISSUE THREAD

**Issue by slavede** [webpack/webpack-dev-server#1069]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**
Currently, we define proxy like this:

```
const PROXY_CONFIG = [
  {
      context: [
          "/api/resource/*",
      ],
      target: "http://localhost:3000",
      secure: false,
      logLevel : "debug"
  },
  {
    context: [
        "/api/*",
    ],
    target: "http://your.remote.backend",
    secure: false,
    logLevel : "debug"
}]
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

While defining the context for proxy, it would be very nice to be able to define a method as well.

```
. . .
context: [{
    url:"/api/*",
    method : "POST"
}]
. . .

```
**If this is a feature request, what is motivation or use case for changing the behavior?**

More freedom while defining mocked APIs.

**Please mention your webpack and Operating System version.**
Webpack 3.4.1
Win 10

**Comment by shellscape** [comment]
@slavede please update your issue using the issue template; the template isn't optional.

**Comment by slavede** [comment]
Done, sorry about that.

**Comment by shellscape** [comment]
@slavede I spent some time reading up about the proxying and proxy config that webpack-dev-server passes along to [`http-proxy-middleware`](https://github.com/chimurai/http-proxy-middleware). Unfortunately, webpack-dev-server doesn't have any say in those options or their structure. Feature requests should probably be made with that project directly.

There _is_ a "Context Matching" capability that you can utilize to filter the method; https://github.com/chimurai/http-proxy-middleware#context-matching. So that might be a good starting point.
