### ISSUE TITLE
[FEATURE] If file not exists in memoryFs and contentBase, proxy to index.html

### ISSUE THREAD

**Issue by MegaUITeam** [webpack/webpack-dev-server#1075]
If file not exists in memoryFs and contentBase folder, then proxy to index.html in memoryFs.
How i can do it? Nothing found in the documentation. Is it possible at all?

**Comment by shellscape** [comment]
hey there. please note that if you see an issue template, it's probably not optional. ours falls into that category and we ask everyone to fill it out. we also close general questions, which this falls issue into. from the issue template:

> Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed.

Closing as question. Please try one of the other outlets listed above for your question.

**Comment by MegaUITeam** [comment]
@shellscape  is FEATURE request!!!!

**Comment by shellscape** [comment]
@MegaUITeam Your issue has two questions within it:

> How i can do it? ...  Is it possible at all?

The issue template also contains:

> **Do you want to request a *feature* or report a *bug*?**

New feature requests outline the feature sought, the use case for the feature, and how it might be implemented, if that applies. Unfortunately, your issue is a question rather than a feature request. If this is merely a language barrier problem, please try opening a new issue in your native language, and **_make sure to fill out the issue template_**, and perhaps someone can translate directly for us.
