### ISSUE TITLE
I get an error "Uncaught TypeError: inherits is not a function" after a rebuild 

### ISSUE THREAD

**Issue by katzz0** [webpack/webpack-dev-server#1076]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I get an error *Uncaught TypeError: inherits is not a function* after the project rebuild.
 
**If the current behavior is a bug, please provide the steps to reproduce.**

I've just updated to webpack 3.5.6 and webpack-dev-server 2.7.1.
Start dev server as usual and it works well util the first rebuild.
After rebuild I get an error *Uncaught TypeError: inherits is not a function*. 

**What is the expected behavior?**
It should run the rebuilded app.

**Please mention your webpack and Operating System version.**
Window 7 x64
webpack 3.5.6
webpack-dev-server 2.7.1
I build Angular 4.3.6

**Comment by shellscape** [comment]
@katzzu thanks for the report. when we see these kinds of errors, it's almost always due to one or a combo of common issues:

- configuration issue in the webpack config
- errant loader or plugin causing problems
- an environment issue preventing a successful rebuild
- an npm cache issue (try clearing your npm cache)
- an npm modules issue (try removing node_modules and reinstalling your modules)

We typically recommend stripping your project down to the bare basics and start triaging from there. Slowly add components of your project back in, and make sure to test at each step. Doing that usually reveals the culprit. 

We'll leave this open as a bug for now in case your triaging exposes a flaw in webpack-dev-server itself.

**Comment by katzz0** [comment]
I've checked the project by narrowing down the search and find out that the source of the problem is `extract-text-plugin@3.0.0`. I checked the resulting JS code after first build and rebuild and for the first build I had module which exports `inherits` function but after rebuild I had require insctructions for that module as it exports `inherits` but it exports an svg image.

I've created an appropriate issue for that plugin and closed this issue.
