### ISSUE TITLE
Doesn't reload on save

### ISSUE THREAD

**Issue by Wavum** [webpack/webpack-dev-server#1128]
* Operating System: Windows 10 Pro N
* Node Version: 8.5.0
* NPM Version: 5.4.1
* webpack Version: 3.6.0
* webpack-dev-server Version: 2.9.1

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

webpack.config.js:
https://pastebin.com/HQvzYH5f

Additional tsconfig.json:
https://pastebin.com/gMQiWVUG

### Expected Behavior
Dev server does reload on save and display the new version from the source.

### Actual Behavior
Dev server compiles on save but doesn't reload the page, when I reload the page manually my new version is not displayed.

### For Bugs; How can we reproduce the behavior?
Use my config and fire up the dev server.

**Comment by shellscape** [comment]
@Wavum we're going to need a very simple, but complete example of this not working correctly. The config you provided is much appreciated, but unfortunately not enough to go on. The functionality you're reporting is a very core, basic functionality of the module and we have a suit of passing tests and working examples that show it does indeed work.  Citing that, this issue qualifies as more of a support question than a bug report, since our examples can be run locally showing that function working properly. With that, we'd like to suggest that you try Stack Overflow or the webpack Gitter to seek some support. In nearly all cases like this, the issue is traced back to an errant plugin or environment issue in a local config.

Of course, you may have stumbled across an edge case. If you can put together a simple repo we can use to reproduce this (free of additional plugins, using only the core webpack-dev-server module) we'll be happy to reopen and examine this issue. For the moment, we're closing this one as a question.

**Comment by andreyvolokitin** [comment]
@shellscape, could this be the same as #1160? If so, here is a minimal test case from ```webpack-dev-server``` repo: https://github.com/webpack/webpack-dev-server/tree/master/examples/cli/hmr. Try changing ```examples/.assets/layout.html``` — it works as described in the issue:  compile happens, but page refresh don't

**Comment by yashrahurikar23** [comment]
I do not know if this would help but if you are working on VS Code there is this limit for watching files that you need to adjust a bit. You can read about it more here
https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc
