### ISSUE TITLE
Provide option to disable addDevServerEntrypoints in CLI

### ISSUE THREAD

**Issue by kesne** [webpack/webpack-dev-server#1138]
* Operating System: macOS
* Node Version: 6.8.1
* NPM Version: 3.10.8
* webpack Version: 3.6.0
* webpack-dev-server Version: 2.9.1

- [ ] This is a **bug**
- [x] This is a **feature** request
- [ ] This is a **modification** request

### Code

N/A

### Expected Behavior

CLI exposes an option to disable `addDevServerEntrypoints`.

### Actual Behavior

No ability to disable `addDevServerEntrypoints` in CLI mode.

### For Bugs; How can we reproduce the behavior?

N/A

### For Features; What is the motivation and/or use-case for the feature?

I use `react-dev-utils/webpackHotDevClient` in my project, which has it's own version of the webpack-dev-server client, but when using the CLI, an additional entry for the client is included. It would be great if there was an option to disable this behavior.

**Comment by shellscape** [comment]
Thanks for checking in with a feature request. Unless there's a high demand for this we're going to have to pass on an option to disable that portion of WDS. That's a pretty core function to the module. In the meantime I'd suggest using the API instead of the CLI. It'll require a few more steps, but you'll have complete control over how WDS is initialized. `react-dev-utils` is also a fairly popular project that's been around a while, so I have to imagine that some folks have found a way around this limitation. I'd encourage you to seek some support from their community.

**Comment by kesne** [comment]
@shellscape Would you accept a pr that accepts a CLI argument to disable the functionality? I know I can do it with the API, I just thought it'd be nice to do it via the CLI if I could.

**Comment by shellscape** [comment]
@kesne not at this time, but really appreciate your willingness to! I'm not convinced it's a good addition to the module, as it doesn't look like the wider demand for that option exists. we're also hard at work on v3 and are really trying not to introduce new features until that lands.
