### ISSUE TITLE
Hot reloading in combination with sass compiling

### ISSUE THREAD

**Issue by katiasmet** [webpack/webpack-dev-server#1140]
* Operating System: OS 10.12.5 (Sierra)
* Node Version: v6.11.0
* NPM Version: 5.4.2
* webpack Version: 3.5.5
* webpack-dev-server Version: 2.7.1

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

or a question

### Code

```js
  // webpack.config.js

  // dev server settings 
devServer: {

    contentBase: configSettings.general.input,
    hot: true,

    overlay: {
      errors: true,
      warnings: true,
    },

    port,

  },

// module rules in development mode
{
          test: /(\.css|\.scss)$/,
          exclude: /node_modules/,
          use: [`css-hot-loader`].concat(extractCSS.extract({
            fallback: `style-loader`,
            // Could also be write as follow:
            // use: 'css-loader?modules&importLoader=2&sourceMap&localIdentName=[name]__[local]___[hash:base64:5]!sass-loader'
            use: [
              {
                loader: `css-loader`,
              },
              {
                loader: `postcss-loader`,
              },
              {
                loader: `sass-loader`,
                options: {
                  sourceMap: true,
                  includePaths: [`src/_scss`],
                },
              },
            ],
          })),
        },
```

### Expected Behavior
I would like to hot replace my code when I save my sass files. Now it replaces when a js-change is made but not when my sass is saved.

I tried several things, but I have to refresh manual to make it work. What worked was using browsersync but I'm wondering if it isn't possible with webpack-dev-server itself. 

I want a clean solution. 

Note: the problem is only in DEV mode! Production mode is ok. 

### Actual Behavior
Everything compiles but when saving a sass-file, I can't see the changes immediately. When I refresh I can see the changes.

### For Bugs; How can we reproduce the behavior?
Using the ExtractTextWebpackPlugin plugin, css hot reloader and sass. I use ExtractTextWebpackPlugin because I don't know another way to make this flow work. I tried several flows. 

### For Features; What is the motivation and/or use-case for the feature?
Don't really know if this is a bug, a question or a feature request for now. But we have a workflow with Inuit CSS framework, that's why we would like to keep the sass-workflow. (Otherwise we could use plain css and that would solve the problem).

**Comment by shellscape** [comment]
@katiasmet thanks for stopping in. unfortunately this qualifies as a support question. 

> Please ask questions on StackOverflow or the
webpack Gitter (https://gitter.im/webpack/webpack). _General questions, how-to
questions, and support requests will be closed._

If you happen to find a bug specifically within webpack-dev-server that is impacting SCSS directly, and not the cause of a third party loader or plugin, please let us know and we'll reopen this. At present though, none of our tests locally have issues with loading css files as part of the bundle and hot reloading when they change. The `modus-iframe` example is a good sample for that. This is more than likely a loader, plugin, or config issue. I'm seeing _a lot_ of activity on Google for scss and hot reaload issues, so that might be a good place to start. [This issue](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/384) looks promising and might yield a fix for you.
