### ISSUE TITLE
HTTPS breaks hot reloading while proxied through browser-sync

### ISSUE THREAD

**Issue by NitsanBaleli** [webpack/webpack-dev-server#1156]
> **Please note that this template is not optional.** If you proceed with this form,
please fill out _all_ fields, or your issue may be closed as "invalid."
Please do not delete this template. Please ask questions on StackOverflow or the
webpack Gitter (https://gitter.im/webpack/webpack). _General questions, how-to
questions, and support requests will be closed._
**Please do remove this header to acknowledge this message.**

* Operating System: ubuntu
* Node Version: v7.6.0
* NPM Version: 4.1.2
* webpack Version: 2.2.1
* webpack-dev-server Version: 2.9.2

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
new BrowserSyncPlugin({
        host: 'localhost',
        port: 3333,
        https: {
          "key": "/home/erez/stuff/xsites/devops/ssl-cert/test.key.pem",
          "cert": "/home/erez/stuff/xsites/devops/ssl-cert/test.cert.pem",
        },
        proxy: 'https://localhost:3030/',
        scrollThrottle: 100
    }, {
        reload: false 
    })
```
### Expected Behavior
browser should reload on js changes, and inject changes on css changes.
### Actual Behavior
nothing happens
### For Bugs; How can we reproduce the behavior?
serving webpack-dev-server output through webpack's BrowserSyncPlugin plugin worked without issues when wasn't https. Once switched to https it gives:
`VM46:1 GET https://localhost:3030/sockjs-node/info?t=1508415256328 net::ERR_INSECURE_RESPONSE`

Im running dev-server with:
`webpack-dev-server --https --client-log-level=error --port=3030 --inline --hot --content-base dist/`

**Comment by shellscape** [comment]
@NitsanBaleli because we know that this doesn't happen _without_ the `BrowserSyncPlugin`, I'm not convinced this is a bug with webpack-dev-server. Have you taken to StackOverflow and/or the webpack Gitter for support on this yet? I'd also suggest creating an issue at https://github.com/Va1/browser-sync-webpack-plugin as your third stop to triaging this issue. I'll lave this open for a bit in the event you find a cause within this module, but we see plugins and loaders screw up WDS all the time, not at the fault of WDS.

**Comment by shellscape** [comment]
@NitsanBaleli please do follow up if this is still a pressing issue. If we reach 30 days without comment it'll be marked as abandoned/stale and closed.
