### ISSUE TITLE
Weird "no code sections found" error

### ISSUE THREAD

**Issue by tquetano-r7** [webpack/webpack-dev-server#1167]
* Operating System: Manjaro (Linux)
* Node Version: 8.8.0
* NPM Version: 5.4.2
* webpack Version: 3.8.1
* webpack-dev-server Version: 2.9.2

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

I'm not sure what is actually causing this, but it appears to only occur on projects where I have `devtool` set to `#cheap-module-source-map`.

### Expected behavior

A build with no logger errors.

### Actual Behavior
Compilation as-of v 3.7.0 (did not exist in 3.6.0 and below) produces random terminal logs of web worker errors in `inspectpack`, which does not actually break builds but produces a lot of noise. No webpack configuration changes happened, just webpack version.

Example:
```
Worker error Error: No code sections found
    at Bundle.validate (/home/{user}/git/{project}/node_modules/inspectpack/lib/models/bundle.js:54:11)
    at createBundle (/home/{user}/git/{project}/node_modules/inspectpack/lib/models/bundle.js:262:12)
    at Immediate.setImmediate [as _onImmediate] (/home/{user}/git/{project}/node_modules/inspectpack/lib/models/bundle.js:313:7)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
```
It happens frequently, although with no consistent pattern, it will just randomly spew it out sometimes.

### For Bugs; How can we reproduce the behavior?

I get it on basically any project that `#cheap-module-source-map` is used on.

**Comment by shellscape** [comment]
@tquetano-r7  this is likely caused by your configuration or environment. in this case I'd say the first place to go would be the [`inspectpack`](https://github.com/FormidableLabs/inspectpack) project. please try stack overflow or the webpack gitter for support otherwise. it's important to examine the context of a problem before creating an issue;

>Compilation as-of v 3.7.0 (did not exist in 3.6.0 and below)

this seems to have little to do with webpack-dev-server, but rather an issue with `inspectpack` or `webpack` itself, and this repo isn't the right place to raise an issue for either.

if you can identify an actual bug and culprit within webpack-dev-server, please let us know. closing as a question.
