### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID error in https

### ISSUE THREAD

**Issue by lourenci** [webpack/webpack-dev-server#1172]
I am getting a https error while trying to run webpack-dev-server over https.

* Operating System: 4.9.59-1-MANJARO GNU/Linux
* Node Version: v8.8.1
* NPM Version: 5.5.1
* webpack Version: 3.8.1
* webpack-dev-server Version: 2.9.4

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Actual Behavior

![image](https://user-images.githubusercontent.com/2339362/32344672-ca6eb59c-bfee-11e7-8d00-fd317e41a45e.png)

**Comment by shellscape** [comment]
@lourenci since you've removed portions of our issue template, your issue is unfortunately invalid. Please re-read the header of the issue template. Stack Overflow or the Webpack Gitter are your support options. 

Since the SSL cert is generated and self-signed, you'll need to click 'ADVANCED' and 'Proceed'. This behavior is expected at the moment. If you'd like to open a PR to modify that behavior we'd be happy to take a look at one.
