### ISSUE TITLE
PORT=xxxx causes portfinder to string concatenate because input is not sanitized

### ISSUE THREAD

**Issue by joltmode** [webpack/webpack-dev-server#1197]
This could be considered an issue on portfinder (https://github.com/indexzero/node-portfinder/blob/master/lib/portfinder.js#L316), though, that's a non-binary-providing library and is not expected to be used with ENV variables. Not their functionality, so to speak. Therefore I am reporting here because I feel this is more like _wrong usage of depending library_.

---

* Operating System: `Linux webapps 4.12.3-1-ARCH #1 SMP PREEMPT Sat Jul 22 15:32:02 UTC 2017 x86_64 GNU/Linux (LSB_VERSION=1.4; DISTRIB_ID=Arch; DISTRIB_RELEASE=rolling; DISTRIB_DESCRIPTION="Arch Linux")`
* Node Version: `v8.2.1`
* NPM Version: `5.3.0` 
* yarn Version: `1.3.2`
* webpack Version: `3.8.1`
* webpack-dev-server Version: `2.9.4`

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code
```
[developer@webapps vue-webpack-latest]$ DEBUG=portfinder:testPort,portfinder:getPort,portfinder.defaultHosts PORT=8090 yarn dev
yarn run v1.3.2
$ webpack-dev-server --inline --progress --config build/webpack.dev.conf.js
  portfinder:defaultHosts exports._defaultHosts is: [ '0.0.0.0', '127.0.0.1', '::1', '10.0.2.15', 'fe80::a00:27ff:fe90:d222', '192.168.56.56', 'fe80::a00:27ff:fe8f:11cf' ] +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +936ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 8090 +2ms
  portfinder:testPort done w/ testPort(): failed 0.0.0.0 w/ port 8090 with error EADDRINUSE +7ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 80901 +0ms
net.js:1458
      throw new RangeError('"port" argument must be >= 0 and < 65536');
      ^

RangeError: "port" argument must be >= 0 and < 65536
    at Server.listen (net.js:1458:13)
    at Object.internals.testPort (/srv/http/javascript-webapps.localdomain/vue-webpack-latest/node_modules/portfinder/lib/portfinder.js:66:18)
    at Server.onError (/srv/http/javascript-webapps.localdomain/vue-webpack-latest/node_modules/portfinder/lib/portfinder.js:57:15)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at Server.emit (events.js:210:7)
    at emitErrorNT (net.js:1339:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior
Port incremented from `8090` to `8091`.

### Actual Behavior
Since `process.env.port` is a string, concatenation happens instead of numeric increment, making the next port `80901` which is out of range.

### For Bugs; How can we reproduce the behavior?
Pass port as ENV variable, and set it to a port already in use.

**Comment by shellscape** [comment]
@joltmode thanks for checking in. a few things:

1. removing the `webpack.config.js` block makes your issue invalid. since it looks like you're green here, we'll give you a pass given all the other info. but keep in mind we didn't just put those placeholders in for fun.
2. your first stop should have been to search this repo for `process.env` to see if this module was doing anything with environment variables. In fact, `process.env` doesn't appear once in code in this repo.
3.  really pay attention to your error stacks, as they can provide crucial info and point you in the right direct. more importantly, they can keep you from heading in the wrong direction, where you spend time posting an issue to the wrong project :)
4. it looks like the fault may lie with the owner of `bootstrap_node.js`, or `vue-webpack-latest` as portfinder is nested under that module's install.

So for numbers, 2, 3, and 4 we're gonna close this one. If we've overlooked something (it happens) please let us know and we'll reopen, but it looks like your issue lies elsewhere.

**Comment by joltmode** [comment]
Oh, f***, messed up badly on my part. :expressionless: 

Sorry for inconvenience.

**Comment by shellscape** [comment]
No worries @joltmode
