### ISSUE TITLE
orphaned node.exe processes on Windows 10

### ISSUE THREAD

**Issue by hansifer** [webpack/webpack-dev-server#1201]
* Operating System: Windows 10
* Node Version: 8.9.1
* NPM Version: 5.3.0
* webpack Version: 3.8.1
* webpack-dev-server Version: 2.9.4

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Expected Behavior

CTRL+C terminates associated node.exe processes.

### Actual Behavior

Running webpack-dev-server (no options) spawns 2 node.exe processes. CTRL+C leaves one of these processes running. This is consistent behavior.

Subsequent attempts to run webpack-dev-server fail with EADDRINUSE if a port is specified in config, otherwise the next available port after 8080 that is not in use is selected. This requires manually killing orphaned node.exe processes every time before running webpack-dev-server to serve from a consistent port.

### For Bugs; How can we reproduce the behavior?

Run webpack-dev-server on Windows 10 command line, observe 2 node.exe processes in Task Manager, stop webpack-dev-server using CTRL+C, observe 1 node.exe process in Task Manager. Repeat to see node.exe processes accumulate in Task Manager.

**Comment by shellscape** [comment]
@hansifer since you chose to remove the code blocks and not provide that for reference, your issue is invalid per the instructions in the issue template.

>  If you proceed with this form, please fill out _all_ fields, or your issue may be closed as "invalid."

the issue you are experiencing is not reproducible, and likely an issue isolated to your specific setup and/or configuration. but we can't really help you there either, because you omitted that information.
