### ISSUE TITLE
Multiple reloads occur in browser when app is changed.

### ISSUE THREAD

**Issue by mcpherson-sa** [webpack/webpack-dev-server#1210]
* Operating System: Ubuntu 16.04 running om VMware Player on Windows 10
* Node Version: 8.9.1
* NPM Version: 5.5.1
* webpack Version: 3.8.1
* webpack-dev-server Version: 2.9.5

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
devServer: {
    contentBase: path.resolve(__dirname, "build"),
    compress: true,
    port: 9000
},
```
### Expected Behavior
Browser should reload once when changes are made to the application.

### Actual Behavior
When I make a change to my application code, wepack recompiles once only, but multiple reloads occur in the browser. The number of reloads is random and ranges from 2 or 3 to 20 odd. I am getting this on chromium 6.2.8 but when I use firefox the problems does not occur. I also tried chrome and the problem is worse if anything. I did some debugging and found that the handler in Server.js in  sockServer.on('connection' is being called multiple time. It seems that when the client connects to the websocket this triggers the 'connection' handlers which triggers another client reload, thus creating a loop. Adding code to_sendStats to delay the call to sockWrite by one second made the issue go away.
Am wondering if anybody else is seeing this. My brother has a similar setup to me but is not seeing the issue. The only other thing I can think that might be relevant is my internet connection is pretty slow and there is reference to external font resource in my webpage.

**Comment by mcpherson-sa** [comment]
I did some more debugging and here is what seems to be going on.

When a page is reloaded due to recompilation, for some reason 2 web socket connections occur. For each connection, 'ok' message are sent s to the client. Without a delay, these message will be seen in the same page context in the client. The first one will see initial as true and then set initial to false. the second one will see initial as false and trigger a reload. 

If the the 'ok' messages are delayed by one second before being sent to the client then when the first ok is sent, the connection it belongs to is now out of scope on the client (as the page has been reloaded) so nothing is received. The second ok is received by the client, and as initial is still true, no page reload occurs.

Hope this helps.

**Comment by shellscape** [comment]
@mcpherson-sa thanks for checking in and for doing some dirty work debugging. unfortunately this isn't something we're able to reproduce on our end or in our tests. it's just not something that we know happens in a regular environment. we ask users to provide all of the info requested in the issue template. unfortunately we have no info on how to reproduce and you've removed one of the code blocks and didn't provide a full config. for all of these reasons we're going to close the issue as a support question. we'd also like to ask you to head over to Stack Overflow or pop in the webpack Gitter to request support for this. usually when we see this kind of odd behavior it's due to an errant webpack config or an environment issue. if you happen to put together a project that can reproduce it on a consistent basis, or you find an edge case that causes this on your end, we can reopen the issue and re-evaluate.

**Comment by mcpherson-sa** [comment]
@shellscape - I think its a shame this issue has been closed so quickly. I would have thought it would make sense to wait a while to see if more people are seeing it, especially since I have shown willingness to help out with the debugging. If you feel I have not provided enough info I would happily provide more.

**Comment by aaroncass** [comment]
I am also seeing this issue ( #1214). I can confirm the issue only occurs in chrome/chromium and not firefox.

I'm new to js so unable to investigate further but I'm happy to provide more info.

**Comment by shellscape** [comment]
@mcpherson-sa closing an issue is an organizational tool. it's not an action that should discourage you. if you feel that our assessment is incorrect, by all means please do dive in. if you find an edge case that can be addressed we'll be happy to reopen to do so.

**Comment by aaroncass** [comment]
My issue (#1214) was closed as a duplicate of this one, but this issue was closed as an edge case because it couldn't be reproduced. It can be reproduced on a standard setup (ubuntu 16.04) with standard installations of node/yarn/chrome . I have tested this on a fresh installation of ubuntu. 
If it helps, I can create a virtualbox image for you to test against.

Please consider reopening this issue.

**Comment by shellscape** [comment]
@aaroncass hm I disagree it's not an edge. I can't reproduce it against any example in the repo across four different OS versions on real, actual machines on my end. if you can create an example that reproduces that behavior cross-platform on multiple browsers, we'd consider that a legit bug. without that consistency, it is indeed an [edge case](https://en.wikipedia.org/wiki/Edge_case)

**Comment by aaroncass** [comment]
Thanks for explaining @shellscape . I will try to reproduce on other systems and report back if I find anything that advances the issue.
