### ISSUE TITLE
Didn't works in IE11

### ISSUE THREAD

**Issue by paveleremin** [webpack/webpack-dev-server#1283]
* Operating System: win10 x64
* Node Version: 8.1.2
* NPM Version: 5.0.3
* webpack Version: 3.10.0
* webpack-dev-server Version: 2.11.0

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

![image](https://user-images.githubusercontent.com/5212490/35101698-7cfea9b0-fc71-11e7-8514-d60e7989df9b.png)

### Expected Behavior
works in IE11

### Actual Behavior
ERROR: SCRIPT1002, didn't works in IE11
Seems it's because of arrow function

**Comment by lydell** [comment]
Hi! This is already tracked in #1278. You can help the maintainers of this repo by closing this issue and 👍:ing the other one!

Also see my analysis of the problem here: https://github.com/webpack/webpack-dev-server/issues/1278#issuecomment-358443674

Luckily, we can just go back to 2.9.7 for the time being :)

**Comment by peduarte** [comment]
Getting the same error on Chrome v44 (i know…)

Upgraded from `2.9.5` to `2.11.0`.

**Comment by SpaceK33z** [comment]
Published `webpack-dev-server@2.11.1` with the fix.

**Comment by peduarte** [comment]
thanks @SpaceK33z will take a look now.
