### ISSUE TITLE
Webpack v4 and v4-beta support

### ISSUE THREAD

**Issue by lencioni** [webpack/webpack-dev-server#1295]
- [ ] This is a **bug**
- [x] This is a **modification** request

Now that webpack v4-beta.0 has been released, there are no more expected breaking changes before the v4 full release in a few weeks. It would be great to publish a version of webpack-dev-server that aims to add support for this new version so folks can start to test their stuff.

I found https://github.com/webpack/webpack-dev-server/pull/1243 which could be a good start for this, but I figured I'd open an issue for folks to track if they are interested in this in general.

**Comment by dschissler** [comment]
I've been caught twice now trying to upgrade Webpack during late beta and getting through the config changes only to realize that it was a waste of time since webpack-dev-server wasn't yet supported.  This happened to me on v1 -> v2 and now v3 -> v4.

I have a question if the serious developers are not using dev-server in their big projects because I can't see how it would be ideal to do a final beta when the two haven't yet been tested together to see if there are unforeseen limitations.  The dev-server isn't as first class as I'd like.  I guess that for now I'll just set this code aside, rollback, remove npm links.  Its annoying.

**Comment by damonbauer** [comment]
@dangodev This was just posted a few hours ago, it might be related: https://medium.com/webpack/webpack-4-import-and-commonjs-d619d626b655

**Comment by dangodev** [comment]
@damonbauer nice! Just read through that. That’s helpful info, but I don’t think that’s affecting this issue.

I [opened an issue on the core repo](https://github.com/webpack/webpack/issues/6483). I’m thinking now it’s a webpack thing, not a webpack-dev-server thing.

**Comment by SpaceK33z** [comment]
Please test the latest beta, `webpack-dev-server@3.0.0-beta.1`. Also be sure to read [the changelog](https://github.com/webpack/webpack-dev-server/releases/tag/v3.0.0-beta.1).

**Comment by dangodev** [comment]
@SpaceK33z when passing arguments via CLI (e.g., `"start": "webpack-dev-server --hot"`), it seems to require installing webpack-cli for yargs. Is this intentional, or a bug?

**Comment by SpaceK33z** [comment]
It intentionally requires webpack-cli, yes.

**Comment by epeli** [comment]
Found couple of issues with the new defaults in Webpack 4.

Versions:

- webpack-dev-server 3.0.0-beta.1
- webpack 4.0.0-beta.1

Config:

```js
var config = {
    mode: "development",
    module: {
        rules: [
            {
                test: /\.jsx?$/,
                exclude: /node_modules/,
                loader: "babel-loader",
            },
        ],
    },
};
```

As the `entry` is not defined following error is thrown:

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   -> The entry point(s) of the compilation.
   Details:
    * configuration.entry should be an object.
      -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
    * configuration.entry should be a string.
      -> An entry point without name. The string is resolved to a module which is loaded upon startup.
    * configuration.entry[1] should be a string.
      -> A non-empty string
    * configuration.entry should be an instance of function
      -> A Function returning an entry object, an entry string, an entry array or a promise to these things.
```

It works if I define it to `entry: "./src/index.js"` but that should not be required with Webpack 4 as it's the default.

Another related thing is that the bundle should be served from `/dist/main.js`. It seems that it's not served at all. This can be fixed by setting:

```js
output: {
    publicPath: "/dist",
},
```

But it's useable otherwise. Thank you!

**Comment by epeli** [comment]
Nope, the weppack command works as expected.

**Comment by SpaceK33z** [comment]
@epeli see #1308 for that error.

I'm going to close this since the latest beta works with webpack v4 now. Let's create separate issues for specific tickets.
