### ISSUE TITLE
Can `inline` be used in options without `webpack-dev-server/client?...` in the entry file?

### ISSUE THREAD

**Issue by GravityMsc** [webpack/webpack-dev-server#1296]
* Operating System:windows 10 pro
* Node Version:8.9.4
* NPM Version:5.6.0
* webpack Version:3.10.0
* webpack-dev-server Version:2.11.1

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
  // webpack.config.dev.js
  entry: {
        index: [
            './src/index.jsx', // some entry files
        ],
    },
  devServer: {
        contentBase: './src/',
        publicPath: '/',
        inline: true,
        hot: true,
        hotOnly: true,
        host: '0.0.0.0',
        port: 8088,
        disableHostCheck: true,
        historyApiFallback: true
  }
```

```js
  // additional code, remove if not needed.
```

### Expected Behavior
  based on the lastest document, `inline` can be used in devServer option. 
  but some files show that `inline  CLI-only`,such as 'lib\optionsSchema.json' 
  ```
  "inline": {
      "description": "Enable inline mode to include client scripts in bundle (CLI-only).",
      "type": "boolean"
    },
  ```
### Actual Behavior
  when use `inline` as devServer option, it seems we don't need use `--inline` and add `webpack-dev-server/client?http://0.0.0.0:8088`?
### For Bugs; How can we reproduce the behavior?
  I just wonder which explaination is corrent and do we need change some decription in files?

**Comment by chrisckc** [comment]
I spotted this and thought i would try it to see if i could simplify my webpack config.

Unfortunately not, I found that i always need to have either 'webpack-dev-server/client' and/or  'webpack/hot/dev-server' in the 'entry' section when using  `--inline` and/or `--hot` on the commandline otherwise the websocket calls are not made and the page never refreshes on changes.

This means that the docs on the inline option are a bit misleading.

**Comment by chrisckc** [comment]
I also found this not to be the case:
https://webpack.js.org/configuration/dev-server/#devserver-hot

>Note that webpack.HotModuleReplacementPlugin is required to fully enable HMR. If webpack or webpack-dev-server are launched with the --hot option, this plugin will be added automatically, so you may not need to add this to your webpack.config.js

Tried that and the page does not load when --hmr is used without the plugin.
Also the wording is a bit odd "so you **may** not need to add this", so that must mean i just have to try it and see then.

**Comment by evilebottnawi** [comment]
Already fixed, you can use `inline` not only using CLI
