### ISSUE TITLE
A vulnerability found in webpack-dev-server

### ISSUE THREAD

**Issue by chromium1337** [webpack/webpack-dev-server#1445]
Hi, I found a vulnerability in webpack-dev-server, how do I report it to you?

**Comment by evilebottnawi** [comment]
@chromium1337 It is problem in dependencies or in `webpack-dev-server` code?

**Comment by chromium1337** [comment]
@evilebottnawi It's in webpack-dev-server code, not dependencies.

**Comment by yagoestevez** [comment]
Hi,
Not sure if it's the same vulnerability. I was just warn by NPM about these vulnerabilities which webpack-dev-server depends on:
![vulnerabilities](https://user-images.githubusercontent.com/36908527/43775984-d0b5ced2-9a4e-11e8-9b90-021a5f8088e3.png)

**Comment by rschultheis** [comment]
👋 Hi I am looking at this issue as it seems to relate to these security advisories:
- https://nvd.nist.gov/vuln/detail/CVE-2018-14732
- https://www.npmjs.com/advisories/725

As far as I can tell, [the fix commit](https://github.com/webpack/webpack-dev-server/commit/f18e5adf123221a1015be63e1ca2491ca45b8d10) has not made it to master nor been released?  Both the NPM Advisory and CVE report a fix version of `3.1.6`, but nothing in [`3.1.6` release](https://github.com/webpack/webpack-dev-server/releases/tag/v3.1.6) looks like the fix for this?  The [`bugfix/origin-header` branch](https://github.com/webpack/webpack-dev-server/compare/bugfix/origin-header) needs a PR and to get merged and deployed.

Am I mistaken or has the fix for this not really been deployed?

This package is widely used so I am looking at this from the perspective of making sure the public data sources are correct.

CC fix commit author @sokra

**Comment by evilebottnawi** [comment]
this package should be used only for `development` purpose, so it is not very high priority

**Comment by evilebottnawi** [comment]
Done in `webpack-dev-server@3.1.11`

**Comment by xhocquet** [comment]
@evilebottnawi Could you please advise the state of this vulnerability in `webpack-dev-server 2.11.3`? Is this vulnerability present, and if so is there a possibility of adding this patch as a security update?
