### ISSUE TITLE
net::ERR_CONNECTION_TIMED_OUT in 1.8.0

### ISSUE THREAD

**Issue by ALF-er** [webpack/webpack-dev-server#146]
After update to 1.8.0 I have strange issue. If I start webpack-dev-server with hot reloading then after few seconds it start spam errors in browser console:
`GET http://localhost/socket.io/?EIO=3&transport=polling&t=1427805624166-18 net::ERR_CONNECTION_TIMED_OUT` in `polling-xhr.js:232`
Browser: Chrome 42
I've created small test repository https://github.com/ALF-er/wp_test/tree/d85de9801747a93c334bc0e24381070c3893a815
(just run `npm run dev` it will start it on localhost:4000)

Am I miss some critical change in 1.8.0?

**Comment by wachunga** [comment]
We are also having issues with 1.8.0. There's a dependency issue downstream with node-xmlhttprequest, which is depended upon by socket.io-client.

```
[15:08:12][Step 1/2] npm ERR! fetch failed https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
[15:09:12][Step 1/2] npm http fetch GET https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
[15:09:12][Step 1/2] npm ERR! fetch failed https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
[15:09:12][Step 1/2] npm ERR! Linux 3.2.0-39-generic
[15:09:12][Step 1/2] npm ERR! argv "node" "/usr/local/bin/npm" "install"
[15:09:12][Step 1/2] npm ERR! node v0.10.21
[15:09:12][Step 1/2] npm ERR! npm  v2.1.5
[15:09:12][Step 1/2] 
[15:09:12][Step 1/2] npm ERR! This request requires auth credentials. Run `npm login` and repeat the request.
```

**Comment by MrOrz** [comment]
@ALF-er Sorry that you bumped into this issue. I made [a pull request](https://github.com/webpack/webpack-dev-server/pull/133) that upgrades socket.io-client used in webpack-dev-server to the latest version, which as a nasty bug.

 In your `webpack.config.js` there is a line:

```js
entry.push("webpack-dev-server/client?/");
```

In theory this should make socket.io-client connect to a socket.io server on `localhost:4000`, since we asked socket.io-client to connect to `/`, and as we are currently browsing `localhost:4000`, the socket.io-client should connect to `localhost:4000` as well.

However, there is an open issue ( https://github.com/Automattic/socket.io-client/issues/812 ) that said socket.io-client would ignore the `:4000` part in the url and connects to port 80, which has no socket.io server and causes timeouts.

Personally I am also having this issue, and my current (and ugly) solution is to open up `node_modules/webpack-dev-server/node_modules/socket.io-client/lib/url.js`, look for `loc.hostname`, change it to `loc.host` and hit save. In the master branch of socket.io-client this fix has already been fixed, but somehow it has not been published yet.

**Comment by talwoolf** [comment]
I am using webpack-dev-server in hot mode when I kee 
I am getting this also? has anyone found or implemented a fix?

**Comment by MrOrz** [comment]
Hi @talwoolf ,
How did you add webpack-dev-server to your webpage? Through `<script src="http://${wp_host}/webpack-dev-server"></script>` or through webpack "entry" config?

It seems that `wp_host` variable is not interpreted to a string correctly.

**Comment by talwoolf** [comment]
I was using the entry point, which seems to break things. when I remove it from the entry point and add it into the index.html it seems to work fine. Any idea why its not working using entry? here is my config:

```export default {
	// devtool : 'eval',
	debug 	: 'true',
	cache 	: true,
	watch   : true, 

	entry   : { 
		'bundle' : [ 
			'./app/browser.js',
			// 'webpack-dev-server/client?http://${WP_HOST}:${WP_PORT}/assets/',
			'webpack/hot/dev-server',
		]
	},

	output : {
		filename 	: "[name].js",
		chunkFilename: "[name]-[chunkhash].js",
		path 		:  contentBase,
		publicPath  : "http://${WP_HOST}:${WP_PORT}/assets/",
	},

	module : {
		loaders: [
	      { test: /\.jpe?g$|\.gif$|\.png$|\.svg$|\.woff$|\.ttf$|\.wav$|\.mp3$/, loader: "file-loader"},
	      { test: /\.js$/, exclude: /node_modules/, loaders: ["react-hot", "babel"] },
	      { test: /\.scss$/, loader: "style!css!autoprefixer?browsers=last 2 version!sass?outputStyle=expanded&sourceMap=true&sourceMapContents=true" }
	    ]
	},

	progress : true,


	plugins : [
		new webpack.HotModuleReplacementPlugin(),
		new webpack.NoErrorsPlugin(),
		
		new webpack.DefinePlugin({
	        "process.env": {
		        BROWSER 	: JSON.stringify(true),
		        NODE_ENV 	: JSON.stringify("development")
	        }
	    }),

		new webpack.optimize.DedupePlugin(),
		new webpack.optimize.OccurenceOrderPlugin()
	]

}```

**Comment by MrOrz** [comment]
You will need some sort of preprocessor for your config to turn `${WP_HOST}` and `${WP_PORT}` into valid strings.
Or you may just replace ${WP_HOST} to the actual value? (ie. `127.0.0.1` or `localhost`)

**Comment by MrOrz** [comment]
@talwoolf I think I get your problem... You are using ES6 syntaxes right? (I mistook `WP_` for wordpress variables in PHP...)

ES6 template strings should be wrapped with ` ` ` (back-tick) rather than single or double quotation marks.

Make sure your node runtime (node --harmony or iojs) support template strings.

**Comment by ALF-er** [comment]
@MrOrz Thank you!

**Comment by talwoolf** [comment]
thanks @MrOrz that worked great

**Comment by SpaceK33z** [comment]
Closing because we're not using socket.io anymore, which caused the issue.
