### ISSUE TITLE
Add a TXT record in the bonjour broadcast for publicPath

### ISSUE THREAD

**Issue by jharwig** [webpack/webpack-dev-server#1482]
* Operating System: macOS High Sierra (10.13.6) 
* Node Version: 10.3.0
* NPM Version: 6.1.0
* webpack Version: 4.17.1
* webpack-dev-server Version: 3.1.6

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```diff
// Add publicPath as a TXT record to bonjour broadcast
bonjour.publish({
  name: 'Webpack Dev Server',
  port: options.port,
  type: 'http',
-  subtypes: [ 'webpack' ]
+  subtypes: [ 'webpack' ],
+  txt: { publicPath: options.publicPath }
});
```
From: https://github.com/webpack/webpack-dev-server/blob/1896fcff8c64390481ad366dd554a8c09c4d1725/bin/utils.js#L94-L99

### Expected Behavior

When receiving a bonjour broadcast it would be handy to know what path the webpack configuration is being served. Currently I have to scrape some html in the `/webpack-dev-server/` route.

### Actual Behavior

No publicPath is available from the broadcast method.

### For Features; What is the motivation and/or use-case for the feature?

My application server (when in dev mode) watches for bonjour messages and routes requests to those servers when they come online, but I don't know the path of the server coming online without scraping html.

**Comment by evilebottnawi** [comment]
@jharwig better disable `bonjour` and use `before/after` to setup own configuration in next major this will be removed in favor `before/after`

**Comment by jharwig** [comment]
Okay that works, thanks for the heads up.

**Comment by mwikstrom** [comment]
@evilebottnawi how to figure out which port to publish when using the `before` approach?

I need to publish webpack's port and public path, preferably using bonjour. Following the suggestion in this thread, I should invoke bonjour explicitly in my `before` callback (instead of relying on the `bonjour` option).

However, the `before` callback gets two arguments: `app` and `server` (no `options` as given to the built-in `bonjour` function).  I can't figure out how to extract which port the server is listening to given those arguments.

**Comment by evilebottnawi** [comment]
@mwikstrom maybe we should pass option too for `before` option, feel free to send a PR

**Comment by jharwig** [comment]
@mwikstrom 
```
before(app, inst) {
    console.log(this.port);
}
```

**Comment by mwikstrom** [comment]
@jharwig Thank you, that's exactly what I needed!

@evilebottnawi Yes, that might be a good idea. However, since the port number is available on `this` it might be sufficient to just document that?
