### ISSUE TITLE
Refactoring broke grunt-webpack

### ISSUE THREAD

**Issue by TheSpyder** [webpack/webpack-dev-server#1483]
The `grunt-webpack` package references a file under `util` directly:
https://github.com/webpack-contrib/grunt-webpack/blob/master/tasks/webpack-dev-server.js#L48

This file moved with commit 2ee13abb96f10c536e02d09abb52377056db372a

Running `webpack-dev-server` 3.1.7, attempting to use `grunt-webpack` now results in:
`>> Error: Cannot find module 'webpack-dev-server/lib/util/createDomain'`

Returning to version 3.1.5 works as before.

If this is intended, I'm happy to log the issue with `grunt-webpack` instead but I thought I'd check here first.

**Comment by michael-ciniawsky** [comment]
Ooops sry :) 

Yes, please send fix to `grunt-webpack` as the `utils/*` are not meant to be a public API of `webpack-dev-server` and could change at anytime 

```diff
- const createDomain = require('webpack-dev-server/lib/util/createDomain');
+ let createDomain

+ try {
+  createDomain = require('webpack-dev-server/lib/utils/createDomain')
+ } catch (err) {
+  createDomain = require('webpack-dev-server/lib/util/createDomain')
+ }
```

**Comment by TheSpyder** [comment]
Sounds good to me, thanks :)

**Comment by nils4iviews** [comment]
Is there any JavaScript-API that could be used instead?

**Comment by nils4iviews** [comment]
I don't mean that you should expose the utils-folder as API. But it seems to me that the `grunt-webpack` project is using the internal API, because there is no documented way to run the dev-server from JavaScript.

I honestly haven't had a closer look, what `grunt-webpack` is really doing with the utils-file, so I can't really tell what they would need. I'm just concerned about a possible break in the future.

But I also don't have the time and the resources to look at it, so I won't bother you with anymore.
