### ISSUE TITLE
when i  npm run dev  i find  in ios safari and not can open my project

### ISSUE THREAD

**Issue by roy201603** [webpack/webpack-dev-server#1511]
* Operating System:IOS
* Node Version:8.11.4
* NPM Version:5.6.0
* webpack Version:3.6.0
* webpack-dev-server Version:2.7.1

- [x] This is a **bug**
when  i npm run dev i find in ios safari and not can open my project 
and also find  
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
/app.js:57856:0
and i search when webpack-dev-server version up 2.7.1 some people have report this problem  
so  i install webpack-dev-server version is 2.7.1  but  no use  so  i need how  to slove this problem 
but in  iphone mobile it will can open   but  in  PC  it is not use  

- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
```

```js
  // additional code, remove if not needed.
```

**Comment by michael-ciniawsky** [comment]
It seems when you bundle your application a tool like e.g `babel` (`babel-loader`) adds a `'use strict';` pragma to the bundle file and depending on the browser (e.g without decent ES2015 (ES6) support) you're using this might leads to the current `{Error}` you're experiencing. Try to remove the pragma from the `app.js` file and check if this fixes your `{Error}`, then checkout how to disable that behavior. I'm closing this issue since it's likely unrelated to `webpack-dev-server` in particular, but feel free to reopen if more information is provided why this maybe related

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack/webpack-dev-server/pull/1270

Updated to at least `webpack-dev-server >= v2.11.0`

**Comment by roy201603** [comment]
![image](https://user-images.githubusercontent.com/25165512/46121053-9e0cbe00-c244-11e8-98cc-a55f08fe1d29.png)
i have install webpack-dev-server to 2.11.3  and not use babel-loader strict mode  so  you think this is babel bring this problem?

**Comment by michael-ciniawsky** [comment]
Either `webpack` or `babel` (`babel-loader`) add  a `'use strict'` pragma (I think it is `babel`). e.g

**`file.js`**
```js
const a = 42
```

**`file.transpiled.js`**
```js
'use strict'; // <= added by babel

var a = 42;
```

yet you **exlude** the `node_modules` folder and one of yur dependencies might use ES6 Syntax which **doesn't** get transpiled atm eventually leading to e.g 

**`file.js`**
```js
import dep from 'pkg'

const a = 42
```

**`file.transpiled.js`**
```js
'use strict'; // <= added by babel

// import dep from 'pkg' (not transpiled)
const dep = true // <= {Error}

var a = 42;
```
