### ISSUE TITLE
Webpack and connect WebSocket (socket.io) via domain

### ISSUE THREAD

**Issue by expertup** [webpack/webpack-dev-server#1659]
- Operating System: Windows 10
- Node Version: v10.15.0
- NPM Version: v10.15.0
- webpack Version: 4.29.0
- webpack-dev-server Version: 4.29.0

- [ ] This is a **bug**
- [ x] This is a **problem**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js

const webpack = require('webpack');

module.exports = {
	entry: './src/index.js',
	module: {
		rules: [
			{
				test: /\.(js|jsx)$/,
				exclude: /node_modules/,
				use: ['babel-loader']
			},
			{
				test: /\.css$/,
				loader: 'style-loader!css-loader'
			},
			{
				test: /\.(png|woff|woff2|eot|ttf|svg)$/,
				loader: 'url-loader'
			}
		]
	},
	resolve: {
		extensions: ['*','.js', '.jsx', '.css']
	},
	output: {
		path: __dirname + '/dist',
		publicPath: '/',
		filename: 'bundle.js'
	},
	plugins: [
		new webpack.HotModuleReplacementPlugin()
	],
	devServer: {
		contentBase: './dist',
		hot: true,
		port: 3000,
		disableHostCheck: true,
		historyApiFallback: true
	}
};
```

I have problem with websocket. I'm using socket.io and socket.io-client in React. When I try connect ws in localhost:5678 this working. But on connect via domain - not.
The port 3000 is my http port, not websocket.

In package.js I have command for start server:
```
"scripts": {
    "start": "webpack-dev-server --config ./webpack.config.js --mode development --host 0.0.0.0"
}
```

How to configure `webpack.config.js` for connect websocket via domain?

**Comment by evilebottnawi** [comment]
Can you provide minimum reproducible test repo, should be works

**Comment by heymath** [comment]
@expertup If I understood your problem, I guess you should check the `public` option [devServer.public](https://webpack.js.org/configuration/dev-server/#devserverpublic).

For my own case:

I got some troubles with my config for Webpack dev server running in a Docker container.
Because of Hot Modules Reload / Web Sockets using the `--host=$HOST` and `--port=$PORT` options that I gave for running the dev server in the Docker container "context", but WS run in the browser in my local machine "context" on `http://my-app.local.my-domain`.

Passing `--public=http://my-app.local.my-domain:80` solved the problem for me 🎉.
Because the dev server is still running on given `--host=$HOST` & `--port=$PORT`, but WS hit on `http://my-app.local.my-domain/sockjs-node/info?t=xxxxxxxxxx`

I hope it helps...

**Comment by evilebottnawi** [comment]
Answer above, thanks
