### ISSUE TITLE
GC Issue, memory leak?

### ISSUE THREAD

**Issue by Siraris** [webpack/webpack-dev-server#1746]
- Operating System: OSX Mojave
- Node Version: 11
- NPM Version: 6.7
- webpack Version: 3.12
- webpack-dev-server Version: 2.11.2

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

Gist of error: 

https://gist.github.com/Siraris/bec8237b399068d24dc9fe7cfa33e210

https://gist.github.com/Siraris/8eae93a12ba4dae741d7008f39e971cc <-- Another error that just occurred after initial submit.

### Expected Behavior
Webpack operates normally.

### Actual Behavior

At random times while webpack-dev-server is running, there is seemingly a memory leak or a GC fault and the dev server crashes.  I'm using foreman as well to start the dev server.

**Comment by evilebottnawi** [comment]
Not sure it is `webpack-dev-server`, i think problem in loader/plugin or your app really is very big (based on files problem in `JSON.stringify()`). We need reproducible test repo, it is impossible fix this issues/problems without repo.

**Comment by Siraris** [comment]
@evilebottnawi So I understand the difficulty in diagnosing this, but I can't think of a reasonable way to provide my organizations source code to you for you to test this, nor can I imagine how i would construct a test repo to reproduce the issue, as it would potentially take me an unreasonable amount of time to do so.  I can convey that my co-workers are running similar hardware and setups to me, and none are encountering this issue.

**Comment by evilebottnawi** [comment]
@Siraris we need snapshot memory. https://medium.com/tech-tajawal/memory-leaks-in-nodejs-quick-overview-988c23b24dba  and https://marmelab.com/blog/2018/04/03/how-to-track-and-fix-memory-leak-with-nodejs.html

Honestly just do memory snapshot something change and do memory snapshot again, repeat it until you get a problem and put here couple snapshots. 

Otherwise it is not fixed never and issue will be close after some time.

**Comment by hiroppy** [comment]
Also, please write detail about your PC spec.

**Comment by Siraris** [comment]
I think this might be due to something I uncovered about our webpack config.  We just implemented a fix and I'm doing some testing to see.

**Comment by evilebottnawi** [comment]
I am closing this issue due `webpack-dev-server@2` is outdated and gets only security fixes, also `webpack@3` has many memory leaks (it was fixed in `webpack@4`), only one solution here - update your deps to latest, sorry but it is very difficult problem and have many leak places, it is hard to fix this
