### ISSUE TITLE
Is it recommended to install this other than as a dev dependency ? 

### ISSUE THREAD

**Issue by LOLdevelopr** [webpack/webpack-dev-server#1828]
- Operating System:
- Node Version: 10
- NPM Version: 6
- webpack Version: 4
- webpack-dev-server Version: 3

I was wondering is it recommended to install this package as dependency other than `development`. 
I think it is really not a good idea to use it in production for sure . May me `global dependency` OK but still isnt it not necessary ?

**Comment by hiroppy** [comment]
Sorry, I don't understand what you said. 

```
$ npm install webpack-dev-server --save-dev
```

Please see the note.

> Note: While you can install and run webpack-dev-server globally, we recommend installing it locally. webpack-dev-server will always use a local installation over a global one.

https://github.com/webpack/webpack-dev-server#getting-started

**Comment by LOLdevelopr** [comment]
i mean , is there any point to install it locally as a dependency ? i mean it should be either installed as a dev-dependency or globally ri8 ?
```bash
$ npm install webpack-dev-server --save-dev      # OK
$ npm install webpack-dev-server -g                    # OK
$ npm install webpack-dev-server --save             # Is this have any point
$ npm install webpack-dev-server --save-optional     # same goes here too, Is this have any point
```

**Comment by hiroppy** [comment]
webpack-dev-server shouldn't be used at production so `--save-dev` or `-g`.
However, development of server side rendering sometimes calls webpack-dev-server from production code. After all, I think that it depends on the idea of the project.
In addition, it is a bad idea to have all developers must install globally because it is desirable to clone the project and just execute `npm i` to make the project work.

**Comment by LOLdevelopr** [comment]
> development of server side rendering sometimes calls webpack-dev-server from production code. 

Is it ? never faced this .

**Comment by hiroppy** [comment]
For example, create-react-app uses webpack-dev-server as dependencies.
https://github.com/facebook/create-react-app/blob/785dd47937cba9892079275b690e6798303b5246/packages/react-scripts/package.json#L79

You can choose `webpack-dev-middleware` or `webpack-dev-serevr`.

In other words, because it depends on the project, there is no answer, but generally it is webpack-dev-server shouldn't be used at production so `--save-dev`.

**Comment by LOLdevelopr** [comment]
I dont think there is a need of `webpack-dev-server` for ssr either.
Thanks @hiroppy for this info. Will do a issue there to get to know about this more .
