### ISSUE TITLE
Support HEAD request

### ISSUE THREAD

**Issue by sindresorhus** [webpack/webpack-dev-server#1833]
See https://github.com/webpack/webpack-dev-server/issues/924#issuecomment-444402288

**Comment by evilebottnawi** [comment]
We already support difference methods (https://github.com/webpack/webpack-dev-middleware#methods), by defaults we supports only `GET`. What is problem? Support by default all possible? Or support only HEAD? Or no documentation about this?

**Comment by sindresorhus** [comment]
What's the purpose of limiting it?

**Comment by evilebottnawi** [comment]
@sindresorhus historical reason, previously we support only `GET` request for webpack-dev-middleware so we support only `GET` for webpack-dev-server, now we support all possible requests for webpack-dev-middleware, but by default we still support only `GET`. We can change this, because i see any problems to allowing any requests. Anyway can you provide case, just for information and future improvements, thanks.

**Comment by sindresorhus** [comment]
I use HEAD request to check whether the server is running.

Another use-case here: https://github.com/webpack/webpack-dev-server/issues/924#issuecomment-482506842

**Comment by evilebottnawi** [comment]
Thanks, mark as feature, feel free to send a PR if you want this asap
