### ISSUE TITLE
Protocol option is overwrited.

### ISSUE THREAD

**Issue by Ne3l** [webpack/webpack-dev-server#2083]
- Operating System: MacOs 10.14.2
- Node Version: 10.15.1
- NPM Version: 6.9.2
- webpack Version: 4.35.2
- webpack-dev-server Version: 3.7.2

- [X] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
module.exports ={
  ...moreSettings
  entry: [
      isDevEnv && `${require.resolve('webpack-dev-server/client')}`,
      isDevEnv && require.resolve('react-dev-utils/webpackHotDevClient'),
      entryPoint,
    ].filter(Boolean),
   ...moreSettings
}
```

```js
// additional code, remove if not needed.
// webpack-dev-server config

module.exports = {
  hot: true,
  inline: true,
  watchOptions: {
    ignored: /node_modules/,
    aggregateTimeout: 300,
    poll: 500,
  },
  publicPath: '/',
  quiet: true,
  https: false,
};


```

### Expected Behavior

Webpack-dev-server respects `http` protocol.

### Actual Behavior

Webpack-dev-server overwrites the `http` protocol with `htttps`

### For Bugs; How can we reproduce the behavior?

In our case we inject the bundle from `http://localhost:3000` inside `https://www.domain.com` that it's mapped to our docker php application. When doing this the socket-js points to `https://localhost:3000` instead of `http://localhost:3000`.

This line seems responsible for this -> https://github.com/webpack/webpack-dev-server/blob/1581adc4cb9067f82da9041c148e2bab4a6762f2/client-src/default/utils/createSocketUrl.js#L50

**Comment by evilebottnawi** [comment]
You should not use `webpack-dev-server/client`

**Comment by evilebottnawi** [comment]
Anyway please create minimum reproducible test repo with example

**Comment by bioPorco** [comment]
Hi, 
I have the same problem. 
For me it's impossible to provide any test case because architecture is a little bit complicated. I have a system composed by 2 webapps. The first webapp is in charge to mantein the user session, the second expose REST Services for a React App. 
Generally the two webapp are in the same jBoss and there is no problem, but for develpment purpose we want to use the first webapp in TEST enviroment and the second webapp in local jBoss. 

So basically I am in the same situation of @Ne3l where I inject the bundle from `http://localhost:8085` inside a page loaded from `https://domain.com`. I have resolved all the CORS (Cross-Origin Resource Sharing)  and Content-Security-Policy problems but HMR (Hot Module Replacement) still point to `https://localhost:8085`.

Is there a configuration that explicity set the protocol to use for HMR? Or the only way is to enable https support for dev server [(devserverhttps)](https://webpack.js.org/configuration/dev-server/#devserverhttps) and handling the complexity introduced by the security layer?

**Comment by bioPorco** [comment]
Ok it seems that the problem is addressed [here](https://github.com/webpack/webpack-dev-server/issues/2302)

**Comment by shynekomaid** [comment]
Overwrote not overwrited!
