### ISSUE TITLE
Chrome Extensions dev

### ISSUE THREAD

**Issue by Dharmoslap** [webpack/webpack-dev-server#214]
It would be great to make webpack-dev-server ready for Chrome Extensions development.

**Comment by schovi** [comment]
@Dharmoslap hello. We are currently developing extension and we use React with Webpack and Hot reload. I try to distil out know-how into clean repo, which can be used as bootstrap for new extensions.
So there it is: https://github.com/schovi/webpack-chrome-extension

**Comment by Dharmoslap** [comment]
Great! :+1:

**Comment by schovi** [comment]
@Dharmoslap Feedbac or Pull requests will be appreciated. I made few more changes and fixes. There was mess with npm packages.

**Comment by Dharmoslap** [comment]
Good, I will implement a simple app using Redux.js and Pull request the result to your repo.

**Comment by SpaceK33z** [comment]
Closing since `webpack-chrome-extension` seems to do the job very well. Feel free to re-open if you think webpack-dev-server should implement this.

**Comment by tonytonyjan** [comment]
@schovi How do you make [Cross-Origin XMLHttpRequest](https://developer.chrome.com/extensions/xhr) with webpack-dev-server?

**Comment by franciscolourenco** [comment]
@SpaceK33z https://github.com/schovi/webpack-chrome-extension directs to https://github.com/schovi/create-chrome-extension which is incomplete and was last updated 3 years ago.

There is a plugin which suggests hot reloading, but instead hard reloads the entire extesion when a content or background scripts changes. Actual pages like options, popup, etc are not supported. https://github.com/rubenspgcavalcante/webpack-extension-reloader

It would be nice indeed to have a plugin or mode which runs the devserver and at the same time build into files which contain the hot module client, so that they can be initially loaded by the browser.
