### ISSUE TITLE
Module parse failed: Unexpected character '@' after upgrading to Webpack v4

### ISSUE THREAD

**Issue by tomraut** [webpack/webpack-dev-server#2339]
- Operating System: OS X
- Node Version: 10.16.3
- NPM Version: 6.9.0
- webpack Version: 4.41.2
- webpack-dev-server Version: 3.9.0
- Browser: Chrome

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

Testrepo can be found there: https://github.com/tomraut/webpacktest

### Expected Behavior
Things should work like they did with Webpack v3 but they're not. I've filed bug earlier here https://github.com/webpack/webpack-dev-server/issues/2322

### Actual Behavior
It gives following error:
```
ERROR in ./app/styles/main.scss 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import "variables";
| @import "mixins";
| 
 @ ./dev-entry.js 6:0-33
 @ multi whatwg-fetch ./dev-entry webpack-dev-server/client?http://localhost:9001 webpack/hot/dev-server

ERROR in ./app/componentList.jsx 54:32
Module parse failed: Unexpected token (54:32)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const list = [
|     // PlayerUI components
>     { name: 'Title', component: <Title asset={asset} configuration={chromecastConfig} />,
|       height: '100px'},
| 
 @ ./app/componentList.jsx-exposed (./node_modules/expose-loader?katsomoPlayer.componentList!./app/componentList.jsx-exposed) 2:60-92
 @ ./dev-entry.js
 @ multi whatwg-fetch ./dev-entry webpack-dev-server/client?http://localhost:9001 webpack/hot/dev-server
```

### For Bugs; How can we reproduce the behavior?
Clone the repo and try it for yourself.

**Comment by evilebottnawi** [comment]
Error number one - you need `sass-loader`
Error number two - remove that https://github.com/tomraut/webpacktest/blob/master/webpack.config.js#L34

**Comment by tomraut** [comment]
@evilebottnawi I've got sass-loader in gulpfile: https://github.com/tomraut/webpacktest/blob/master/gulpfile.js#L74

**Comment by tomraut** [comment]
@evilebottnawi removing L34 from webpack.config.js didn't help, still getting this error:
```
ERROR in ./app/componentList.jsx 54:32
Module parse failed: Unexpected token (54:32)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file
```

**Comment by tomraut** [comment]
@evilebottnawi please note that this same setup works without any issues when I use "webpack": "3.11.0" and "webpack-dev-server": "2.11.1".

**Comment by evilebottnawi** [comment]
Problem no in dev server, problem in your setup, please read migration guide before migrate and use stackoverflow for questions because it is bug tracker, not QA service.
1. You don't need https://github.com/tomraut/webpacktest/blob/master/webpack.config.js#L14 - remove that, dev server automatically enable this plugin
2. You don't need `webpack/hot/dev-server` and `'webpack-dev-server/client?http://localhost:' + port` https://github.com/tomraut/webpacktest/blob/master/gulpfile.js#L77, dev server automatically include these stuff 
3. update all deps to latest
4. Don't use `Object.create` https://github.com/tomraut/webpacktest/blob/master/gulpfile.js#L56, please read how `Object.create` works
5. Create babel config:
**.babelrc**
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ]
}
```
6. Open http://0.0.0.0:9001/components.html

I don't know your structure and don't know what exactly expected so use stackverflow or gitter for advices

**Comment by tomraut** [comment]
Many, many thanks, @evilebottnawi , got it working now, awesome!
