### ISSUE TITLE
Upgrade version of Chokidar

### ISSUE THREAD

**Issue by yotamshapira** [webpack/webpack-dev-server#2351]
- Operating System: MacOS Catalina 10.15.1
- Node Version: v12.6.0
- NPM Version: 6.9.0
- webpack Version: 4.39.2
- webpack-dev-server Version: 3.9.0
- Browser: Chrome

- [ ] This is a **bug**
- [X] This is a **modification** request

### Code

```js
// N/A
```

### Expected Behavior
Should remain the same

### Actual Behavior
Normal, this is a dependency upgrade

### For Bugs; How can we reproduce the behavior?
N/A

### For Features; What is the motivation and/or use-case for the feature?
Upgrading dependencies is considered to be a good practice :)

**Comment by evilebottnawi** [comment]
Can be done only for next version

**Comment by Nickhoyer** [comment]
@evilebottnawi Can you provide further information on why this can only be done for next version? Right now we cannot use npm ci on windows until this has been updated. Webpack-dev-server is the only dependency we have that runs an earlier version of chokidar, and we can't switch to next version, since our project uses cra/react-scripts for managing this.

**Comment by evilebottnawi** [comment]
Because it is breaking change for the current version
