### ISSUE TITLE
vulnerabilities 

### ISSUE THREAD

**Issue by martinoppitz** [webpack/webpack-dev-server#2399]
https://snyk.io/test/npm/webpack-dev-server/3.10.1?tab=dependencies

- https://snyk.io/test/npm/http-proxy-middleware/0.20.0 (vulnerabilities 0)
- https://snyk.io/test/npm/chokidar/3.3.1 (vulnerabilities 0)

Thank you

**Comment by evilebottnawi** [comment]
Please open issue in `kind-of` repo, they should do security patch release

**Comment by kevin-brown** [comment]
I've been tracking back packages which depend on `kind-of` because of the latest security releases. `kind-of` released a new version last week which fixes the security issues. They don't appear to have marked older versions as vulnerable though, which is fun.

`chokidar@2.1.8` (through the giant dependency tree) depends on `kind-of@3` and `kind-of@4`, both of which are vulnerable and will not have security patches released (as far as I know). `webpack-dev-server` depends on `chokidar@2.1.8`.

`chokidar@3` exists and appears to not have the specific dependency tree that I'm tracking right now. I would urge `webpack-dev-server` to consider updating to this new major version of `chokidar`.

**Comment by evilebottnawi** [comment]
We can't update chokidar because it is breaking change for us

**Comment by evilebottnawi** [comment]
Will be great if developers of `kind-of` backport security fix for 3 and 4 version

**Comment by evilebottnawi** [comment]
Fixed on side of `kind-of`
