### ISSUE TITLE
Webpack dev server overlay doesn't work.

### ISSUE THREAD

**Issue by bobahvas** [webpack/webpack-dev-server#2414]
# Bug report

**What is the current behavior?**
I can see errors in google chrome console, but don't see overlay with errors

**If the current behavior is a bug, please provide the steps to reproduce.**
Clone https://github.com/vuejs/vue-next-webpack-preview
Add in any place code with error, for an example `const a = b.c;`

**What is the expected behavior?**
I want to see overlay with errors over current page like I saw before

**Other relevant information:**
webpack version:  4.41.4
Node.js version: v12.14.1
Operating System: Windows
Additional tools:

**Comment by evilebottnawi** [comment]
It is expected, because it is valid code, we show the overlay only when we have a compilation problem, but here all fine (no syntax or compilation problems), it is runtime error, in theory we can put `try/catch` and catch runtime errors, but it is not good idea, also runtime errors better look in dev tools (stack/links on files/source maps/etc), feel free to leave feedback

**Comment by bobahvas** [comment]
@evilebottnawi thank you for your answer.
I understand, but in some cases it very useful. Will be great if we can set optional parameter for this feature.

**Comment by evilebottnawi** [comment]
As I said above, using `try/catch` on whole code can potential break some cases and apps, it is not safe
