### ISSUE TITLE
Upgrade to chokidar 3 to support the Node v14 release

### ISSUE THREAD

**Issue by dandv** [webpack/webpack-dev-server#2528]
Saw this warning while installing a Gatsby project:

> warning gatsby > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to [chokidar 3](https://www.npmjs.com/package/chokidar/v/3.0.0) with 15x less dependencies.

Indeed, [our `package.json` depends on chokidar 2](https://github.com/webpack/webpack-dev-server/blob/master/package.json#L41).

**Comment by hiroppy** [comment]
Sorry but we can't upgrade Chokidar to v3 because this library doesn't support Node6 but webpack-dev-server needs to support Node6.

**Comment by paulmillr** [comment]
You should release webpack 5 with node 8+ / chokidar 3 support and make "webpack-dev-server-next" webpack 6. It really IS a big deal. It's a security issue. See #2376.

**Comment by evilebottnawi** [comment]
@paulmillr You **should not** tell us how to make a release roadmap. In the near future we will remove `chokidar` in favor better alternative

@hiroppy I would rather refuse `chokidar`, in favor native or https://github.com/facebook/watchman 

But after testing the native support, I did not find any problems with native fs washing with the latest LTS versions of the node.

Besides problems, it brings bad supporting + lead developer abusive behavior + only bla-bla-bla, "it will freeze", "it will slow down", "it will not work" without any real examples, reproducible test repos or just code examples, also I would like to raise an issue on npm about security problems, because @paulmillr say that they do not have access for AWS from previous versions :confused: 



It all sounds just awful. I have no words.

**Comment by hiroppy** [comment]
Yes, watchman is cool but many options don't support this library, too sad.

https://facebook.github.io/watchman/docs/nodejs/

**Comment by dandv** [comment]
I know very little about this, but I've just noticed that [the Linux binary for watchman is bigger than some Linux distros](https://github.com/facebook/watchman/issues/804).

**Comment by evilebottnawi** [comment]
@dandv native fs works fine, we should consider migration, no more compilation and platform dependent libraries, also this will give a huge set of feedback and potentially we can improve native fs watching on node.js side, because in our long-term we must get rid of unnecessary dependencies in favor of abilities node.js platform

**Comment by tmm1** [comment]
On node 14.2.0, I'm noticing that `webpack --watch` will now consume 180-200% CPU constantly. Presumably this is because of the chokidar v2 incompatibility.

<img width="366" alt="Screen Shot 2020-05-07 at 2 19 08 PM" src="https://user-images.githubusercontent.com/2567/81345694-c938cf80-906d-11ea-9e0b-28dd43e18419.png">

**Comment by tmm1** [comment]
> Presumably this is because of the chokidar v2 incompatibility.

I can confirm this was the case. I used yarn and added the following to my package.json:

```
  "resolutions": {
    "chokidar": "^3.4.0"
  }
```

and now CPU usage is back to normal.

**Comment by sibelius** [comment]
node 12 is the LTS now

we should deprecate node 6 to seek performance gains

**Comment by SomethingNew71** [comment]
Yeah, I am not sure why Node 6 should even be a consideration at this point.... 

It's not even remotely supported at this point.

![schedule](https://user-images.githubusercontent.com/4572799/85577024-e66a3300-b606-11ea-9f21-f9671e110d67.png)

**Comment by evilebottnawi** [comment]
We are working on v4, a lot of changes, nobody want to help, but we are open source project

**Comment by paulmillr** [comment]
@evilebottnawi that's not "a lot of changes". You bump to v5 and release with new chokidar. That's it. Takes five minutes.

**Comment by evilebottnawi** [comment]
@paulmillr nope

**Comment by sibelius** [comment]
can you accept a PR to fix this?

**Comment by dandv** [comment]
Why is this issue <kbd>Closed</kbd> to begin with?

**Comment by evilebottnawi** [comment]
It is fixed in v4, release is soon

**Comment by toresbe** [comment]
> I know very little about this, but I've just noticed that [the Linux binary for watchman is bigger than some Linux distros](https://github.com/facebook/watchman/issues/804).

For what it's worth: This was all debug symbols accidentally included by the CI. As indicated by the link, that issue is resolved. I am looking forward to the v4 release, whether that's a chokidar bump or a switch to watchman :)

**Comment by mmunte-impeo** [comment]
@alexander-akait  so many dependent software is not able to properly work on nodejs 15 because you do not release an updated version with chokidar 3. 

It was june when you wrote version 4 would be released soon. 

Sure it is open source, but still I agree with other saying it is such a simple fix. Those using yarn can bypass the problem using resolutions. But those using npm - no luck. 

Nodejs 15 will support Apple Silicone. There is no official build yet, but it compiles fine from sources. But then using the webpack-dev-server will, as others wrote, consume 120% cpu constantly. 

Hope you can reconsider.

**Comment by alexander-akait** [comment]
We do release webpack-dev-server4-beta.0 with latest chokidar
