### ISSUE TITLE
NPM release with the lastest from master

### ISSUE THREAD

**Issue by mvegacr** [webpack/webpack-dev-server#2549]
For fixing the jQuery vulnerability reported on this issue: https://github.com/webpack/webpack-dev-server/issues/2515, is there a date when it can be released to npm?

Thanks for all the help!

**Comment by evilebottnawi** [comment]
Release will be soon, please be patient

**Comment by MagicLegend** [comment]
@evilebottnawi Any updates? I noticed that the documentation is not just for the released version, but for master. That took me quite a bit to figure out. Maybe you should push the documentation together with a release; since now the documentation makes it sound like [devserver open](https://webpack.js.org/configuration/dev-server/#devserveropen) takes an object.

**Comment by evilebottnawi** [comment]
@MagicLegend We will update documentation before release, where is not big changes, just refactor options and remove outdated code

**Comment by MagicLegend** [comment]
Fair enough. Maybe I would suggest keeping the staged documentation changes ready in a PR on the documentation-repo; and not pulling that until the updated package is available on NPM.

Any updates on actually pushing the changes to NPM? I'm relying on being able to pass the `--remote-debugging-port=9222` flag to Chrome. I'm unable to push my config changes until this package gets updated (I patched it locally).

**Comment by evilebottnawi** [comment]
@MagicLegend 

Yes, I agree, we have an issue for this and the next versions will always immediately make changes to the documentation
