### ISSUE TITLE
[webpack v5] libraryTarget=var doesn't expose the entry module

### ISSUE THREAD

**Issue by LexSwed** [webpack/webpack-dev-server#2881]
# Bug report

**What is the current behavior?**

After upgrading to `webpack@5` builds no longer expose modules when `output.libraryTarget = 'var'`, global variable always points to an empty object instead of the entry point module

**If the current behavior is a bug, please provide the steps to reproduce.**

Having config
```js
 // config
  entry: {
    app: './src', // seems like it works correctly for { entry: '.src/' } though
  },
  output: {
    library: {
      name: 'app2',
      type: 'var',
    },
  }
```

load a script build with such config on the page and try to access `window.app2` variable, it should point to the entry module. It is an empty object instead.

See [simple reproduction](https://github.com/LexSwed/webpack-5-issue)

**What is the expected behavior?**

Having `libraryTarget: 'var'` exposes global variable pointing to the entry point module

webpack version:  5.x
Node.js version: 12.x
Operating System: MacOS

**Comment by alexander-akait** [comment]
Fixed in `webpack-dev-server@4-beta.0`, please try and put feedback

**Comment by nicmosc** [comment]
Had the same issue myself with `webpack-dev-server@3.11`, where the libraryTarget when set to `umd` would just expose an empty object. Here is a simplified config:
```
entry: { tourama: './src/index.tsx' },
  output: {
    publicPath: '/',
    path: path.resolve(__dirname, 'dist'),
    libraryTarget: 'umd',
    library: 'tourama',
  },
```

And the `index.html`:
```
 <div id="tourama-container"></div>
    <script src="/tourama.js"></script>
    <script type="module">
      import config from './tourama.config.js';
      console.log(tourama)
      tourama.init(config, '#tourama-container');
    </script>
```
Where the log would print `{}` for the exposed library. This is fixed in `webpack-dev-server@4`, but then _all_ hot reloading is broken (and support for Fast Reload is lost since those plugins don't support version 4 yet). Here is the config I have for the `devServer` with the broken hot reload:
```
config.devServer = {
    historyApiFallback: true,
    host: '0.0.0.0',
    port: WEBPACK_PORT,
    liveReload: true,
    injectClient: true,
    client: {
      logging: 'none',
      progress: false,
      overlay: false,
      host: '0.0.0.0',
      port: WEBPACK_PORT,
    },
    static: [path.join(__dirname, '/'), path.join(__dirname, 'node_modules')],
  };
  config.infrastructureLogging = {
    level: 'none',
  };
  config.stats = 'errors-only';
```

Do you know if there's a way of getting Hot Reload to work with version 4? We can always wait for those plugins to add support since this is still in Alpha, but I don't think it's fair needing to upgrade to an alpha version for a bug which is pretty big in V3.
