### ISSUE TITLE
Upgrade http-proxy-middleware due Websocket Issue in 3.x branch

### ISSUE THREAD

**Issue by Delagen** [webpack/webpack-dev-server#3004]
Webpack: 3.11.1

```js
// proxy.json
{
 "/ws/": {
    "target": "wss://some-server.ru",
    "changeOrigin": true,
    "logLevel": "debug",
    "ws": true
  }
}
```

### Expected Behavior
No errors

### Actual Behavior
Any WS connection to server during work cause
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:213:20)
with crash

### For Features; What is the motivation and/or use-case for the feature?
Update version of middleware or make it less precise

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Do not ignore how we can reproduce it, `Error: read ECONNRESET` means ws can't connect

**Comment by Delagen** [comment]
Yes, but it crash entire dev-server

**Comment by alexander-akait** [comment]
@Delagen Sorry using your information in the issue template I can't help you, I think nobody can help

**Comment by Delagen** [comment]
Why you simply cannot upgrade package in webpack 3.x version?

**Comment by alexander-akait** [comment]
Because it will be breaking change, it updated for v4 (beta)

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack-dev-server/blob/master/package.json#L48, we are working on new release
