### ISSUE TITLE
"webpack-dev-server": "^4.0.0-beta.2" no work fine, 404

### ISSUE THREAD

**Issue by YanYuanFE** [webpack/webpack-dev-server#3264]
- Operating System: Mac OS
- Node Version: v15.12.0
- NPM Version: 7.6.3
- webpack Version: 5.36.0
- webpack-dev-server Version:4.0.0-beta.2
- Browser: chrome 90

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```
devServer: {
    port: 8080,
    compress: true,
    hot: true,
    dev: {
      // writeToDisk: true,
      publicPath: resolve("./dist"),
    },
    static: false,
    // static: {
    //   staticOptions: {
    //     contentBase: resolve("./dist"),
    //   },
    //   directory: resolve("./dist/static"),
    // },
    setupExitSignals: true,
  },
```js
// additional code, remove if not needed.
```

### Expected Behavior

work fine

### Actual Behavior

404

### For Features; What is the motivation and/or use-case for the feature?

https://github.com/YanYuanFE/react-ts-app

yarn && npm start

**Comment by YanYuanFE** [comment]
Is my configuration wrong? What should be the correct configuration?

**Comment by alexander-akait** [comment]
Please avoid using `beta` if you don't read changelog, we will update docs when it will be stable. 

Firstly:
- You need set `static: resolve("./public")` on directory where you have `index.html`
- Don't override `publicPath: resolve("./dist")` in `devServer`, because it is needed only when you proxy dev server
- Set right `output.path`
- Don't set `output.publicPath`, default value `auto` is the best solution.

**Comment by YanYuanFE** [comment]
Thanks。
