### ISSUE TITLE
Cannot GET URLs with extension with historyApiFallback: true

### ISSUE THREAD

**Issue by kirill-konshin** [webpack/webpack-dev-server#332]
If I enter address like `http://localhost:3000/foo` everything works as expected, even `http://localhost:3000/foo/bar/baz` works too.

But addresses with extension `http://localhost:3000/foo.html` always return `Cannot GET /foo.html`.

**Comment by kirill-konshin** [comment]
I fixed it by adding the following to my webpack config (instead of `historyApiFallback: true`):

```
historyApiFallback: {
    rewrites: [
        {from: /.*\.html/, to: '/index.html'}
    ]
},
```

But I suspect this should be a default behavior...

**Comment by ramboza** [comment]
Thanks !!! it works !

**Comment by eryshev** [comment]
I have the same issue one year  later, thx @kirill-konshin for the solution.

**Comment by mirkonasato** [comment]
Had the same issue with a route mapping like `/item/:id` where the `id` value just happened to contain a `.` sign.

However looks like webpack-dev-server just uses connect-history-api-fallback, that since 1.3.0 supports a [disableDotRule option](https://github.com/bripkens/connect-history-api-fallback/issues/25#issuecomment-238067217).

Still, not sure why it's not the default.

**Comment by SpaceK33z** [comment]
closing because this is not an issue in webpack-dev-server and there have been multiple answers.
