### ISSUE TITLE
Chokidar Dependecy Upgrade for v3

### ISSUE THREAD

**Issue by nVitius** [webpack/webpack-dev-server#3339]
@alexander-akait I know that you have closed all the issue requesting this change by saying that it is a "breaking change". While I do understand the reasoning behind this, it is worth considering that versions older than node 8 (the earliest release supported by chokidar v3) have been out of LTS for years now. There is no obligation to continue to support these versions. Not to mention that chokidar v2 will cease to work versions of node 14+ (the current LTS). Should support for those versions not be more important?

I know that the release of v4, which does include this upgrade, is imminent. Most of the time this repo is downloaded as a sub-dependency of something else. This implies that all projects will have to upgrade their dependency on webpack-dev-server before this issue can be called fixed. I don't know what changes are planned for v4, but I'm assuming that, since it is a "major" version change, they will require some work to integrate with.

Also consider that chokidar v2 does not have support for the new Apple M1 chips. I'm not using one, but apple products are extremely common among the node/js community.

I'm sure that I'm not alone in saying that making this upgrade would save a lot of trouble for a lot of people. I would ask you to please reconsider your stance on this issue or at least give us solid reasoning on why this change will not be made.

**Comment by alexander-akait** [comment]
We just can't do it, because it is breaking change, even if i just bring up the version of `chokidar` I need to release v4 (I can not do breaking change under patch/minor release), so other products/boilerplates still need to update webpack dev server, just use `beta`, it is stable, we just need to finish our API inside, but if you use `webpack serve` it will be stable for you

**Comment by davidpocina** [comment]
@nVitius chokidar v3 is pretty much backwards compatible.

You can force a newer version in `package.json`
````
  "resolutions": {
    "chokidar": "^3.5.0"
  }
````

**Comment by nVitius** [comment]
@alexander-akait Thank you for your reply. I still don't understand how this is a breaking change. The API is fully backwards-compatible and will not change anything for webpack-dev-server aside from dropping support for some older node versions. Versions which have been out of LTS for _years_.

I cannot use the beta version of v4 as it is being imported as  a sub-dependency.

Thank you for your contributions to this project. I appreciate how much effort goes into a project like this; I don't mean to take up your time on an issue that might seem trivial. If the decision on this is final, please close out the issue.



@davidpocina This only works if you use yarn instead of npm.

**Comment by alexander-akait** [comment]
> dropping support for some older node versions

problem here, I can not violate semver...

> I cannot use the beta version of v4 as it is being imported as a sub-dependency.

Why?

**Comment by mvz** [comment]
As far as I can tell from https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api, semver would allow for this. People running very old versions of node would simply not be able to update to the latest webpack-dev-server v3.

**Comment by pwilkowski** [comment]
+1 for this. 

I keep seeing this warnings from every single angular project we have and as time goes on our devs are getting scared.

Normally you wouldn't be scared to see a warning right? Wrong. Because this warning contains scary phrases such as:

_Chokidar 2 **will break** on node v14+_
_could be using **insecure binaries**_

And the thing is. Node v14 is pretty much the only node version that also allows us to run other stuff painlessly. 
So we are in this place that anything below is too old AND current version is "too new". 
And every little small update on our local environments to node version can potentially break a lot of projects.
Solutions like `nvm` won't even help as some of the packages we use inside same project requires 14+

Isn't it a good time to simply let go and move on?


Full warning logs from JUST `webpack-dev-server` and nothing else in the project (literally `npm init` and adding this package):
```
warning webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning webpack-dev-server > sockjs > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning webpack-dev-server > webpack-log > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning webpack-dev-server > http-proxy-middleware > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning webpack-dev-server > http-proxy-middleware > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated```

**Comment by ljharb** [comment]
Dropping any node version, LTS or not, is always a breaking change, full stop.

**Comment by alexander-akait** [comment]
@ljharb yep, I think the same.

**Comment by alexander-akait** [comment]
@nVitius we fix last things and will do rc release on the next week (maybe earlier)

**Comment by alexander-akait** [comment]
in the future I will revise our release policy and we will get rid of such long releases, big sorry

**Comment by nVitius** [comment]
I think we can call this issue closed. Thanks to everyone for their input.
