### ISSUE TITLE
Error: spawn webpack serve ENOENT

### ISSUE THREAD

**Issue by ydCao** [webpack/webpack-dev-server#3349]
- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

**Comment by ydCao** [comment]
Error: spawn webpack serve ENOENT

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please fill out all fiends, we can't help you using `Error: spawn webpack serve ENOENT` information, double check you are installed `webpack-cli`
