### ISSUE TITLE
Watch files not required with webpack

### ISSUE THREAD

**Issue by gunta** [webpack/webpack-dev-server#34]
Hi! Would it be possible to add to webpack-dev-server and middleware an option to watch also files outside the required ones?
This is needed specially for the HTML files, and maybe some css ones.

Thank you!

**Comment by tomekwi** [comment]
+1 for this feature

**Comment by Ciantic** [comment]
Is this possible or not?

**Comment by jdeal** [comment]
Bit of a janky solution, but I used the text-loader module to do something like this. (In my case, CSS generated outside of webpack, but same principal.)

Basically, just `npm install text-loader` and then make a `watch.js` entry point (which you'll not actually use). In your `watch.js` file, add in text files like:

```
require('text!./app/worksheet.html');
```

That way, `watch.js` will get changed any time you change `worksheet.html`, and your app will get reloaded.

A better variant of this would be to have a "hash-loader" which would just MD5 hash the content and use that instead of the actual content, because in this case you don't actually need the content, just something to notify that there's a change. Should be pretty easy to create such a loader.

**Comment by airwin** [comment]
+1

**Comment by jaredleechn** [comment]
👏

**Comment by SpaceK33z** [comment]
Closing issue because the answer provided is clear; make a loader for this, or use an existing one :).

**Comment by thatbignerdguy** [comment]
Did anyone ever come up with a solution for this? It doesn't seem like `fileDependencies` or `contextDependencies` exist anywhere.

**Comment by dudewad** [comment]
@sokra shouldn't this be `compiler.plugin('after-compile'...`? I can't find any hooks anywhere called `after-compiler`.

**Comment by Fridus** [comment]
Hi, try this : https://github.com/Fridus/webpack-watch-files-plugin ;)

**Comment by sap9433** [comment]
Just wrote a plugin that does exactly the same - solves your problem - https://www.npmjs.com/package/filewatcher-webpack-plugin .

@Fridus looks like this 1 got move power under its sleeve.

**Comment by ivanm376** [comment]
possible problem for Linux users see https://webpack.js.org/configuration/watch/#not-enough-watchers
