### ISSUE TITLE
webpack-dev-server requires page reload after a syntax error in the code.

### ISSUE THREAD

**Issue by DenysPavlenko** [webpack/webpack-dev-server#3401]
Reload stops working and requires browser reload after a syntax error occur in the code.

"webpack": "^4.20.2",
"webpack-cli": "^3.1.2",
"webpack-dev-server": "^3.11.2"

Here is my webpack config file:

const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'dist'),
  },
  devServer: {
    contentBase: path.join(__dirname, 'src'),
    hot: true,
    port: 3000,
  },
  plugins: [
    new HtmlWebpackPlugin({
      title: 'Development',
    }),
  ],
};

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please fix it and I will reopen and help. 

You don't need to set `contentBase: path.join(__dirname, 'src')`, contentBase is `public` directory, you don't need to watch source of code, webpack do it itself
