### ISSUE TITLE
Virtual file in the output parent directory is not served

### ISSUE THREAD

**Issue by dmtkpv** [webpack/webpack-dev-server#3580]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

https://github.com/dmtkpv/dev-server-issue

### `webpack-cli info`
```
System:
  OS: macOS Mojave 10.14.6
  CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
  Memory: 31.08 MB / 8.00 GB
Binaries:
  Node: 16.1.0 - /usr/local/bin/node
  npm: 7.11.2 - /usr/local/bin/npm
Browsers:
  Chrome: 92.0.4515.107
Packages:
  html-webpack-plugin: ^5.3.2 => 5.3.2 
  webpack: ^5.47.1 => 5.47.1 
  webpack-cli: ^4.7.2 => 4.7.2 
  webpack-dev-server: ^3.11.2 => 3.11.2 
```

### How can we reproduce the behavior?

- clone the repo
- install modules `npm install`
- run dev server `npm run serve`
- go to http://localhost:49030/index.html

### Expected Behavior
Browser shows generated index.html file

### Actual Behavior
I'm able to access http://localhost:49030/build/main.js
HtmlWebpackPlugin filename is `../index.html` and publicPath is `/build/`
So index.html should be available by http://localhost:49030/build/../index.html which is http://localhost:49030/index.html
But browser shows `Cannot GET /index.html`

**Comment by alexander-akait** [comment]
You have wrong `publicPath`, please use `publicPath: '/'`, because you use `path.join(__dirname, 'public/build')`, you will have `/public/build/public/` path (try http://localhost:49030/build/), we described it in docs, using `../index.html` is not solve the problem, because your output file above `output.path` and so dev server can handle this (we handle request based on `publicPath`). Anyway we strongly recommend to use `publicPath: auto` (note your need polyfill `currentSrc` for IE11), so all your URLs will ahve relative path and you will not faced with the problem again, feel free to feedback

**Comment by dmtkpv** [comment]
@alexander-akait 

> You have wrong publicPath

`publicPath` is not wrong
The directory that will be served in production **(not via webpack-dev-server)** has the following structure:
```
public
├──build
│   └── main.js (bundle)
└──index.html
```
For example, if the domain name is *example.com*, then the file URLs would be:
*example.com/index.html*
*example.com/build/main.js*

The same URLs should be available on localhost via webpack-dev-server
I have the following `webpack.config.js`
 
```javascript
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {

    plugins: [
        new HtmlWebpackPlugin({
            filename: '../index.html'
        })
    ],

    devServer: {
        contentBase: 'public',
        port: 49030
    },

    output: {
        path: path.join(__dirname, 'public/build'),
        publicPath: '/build/'
    }

}
```
 `publicPath` specifies the **public URL** of the output directory when referenced in a browser
 
Output directory is `path.join(__dirname, 'public/build')`
Bundle file path will be `path.join(__dirname, 'public/build/main.js')`

Setting `publicPath` to `'/build/'` makes bundle file available by [localhost:49030/build/main.js](http://localhost:49030/build/main.js) which matches production URL (*example.com/build/main.js*)

**Comment by dmtkpv** [comment]
> please use publicPath: '/'
 
Setting `publicPath` to `'/'` makes bundle file available by [localhost:49030/main.js](http://localhost:49030/main.js) which does not match production URL (*example.com/build/main.js*)

**Comment by dmtkpv** [comment]
> because you use path.join(__dirname, 'public/build'), you will have /public/build/public/ path (try http://localhost:49030/build/)
 
 Sorry, I can't grasp the meaning of this sentence

**Comment by dmtkpv** [comment]
> using ../index.html is not solve the problem, because your output file above output.path and so dev server can handle this (we handle request based on publicPath)
 
> dev server **can** handle this

Dev-server does not handle `../index.html`. That's the issue. Virtual file in the output parent directory is not served

**Comment by dmtkpv** [comment]
> Anyway we strongly recommend to use publicPath: auto

Setting `publicPath` to `'auto'` does not fix the issue.

**Comment by alexander-akait** [comment]
As I written before we really on output.path +  publicPath, you output file above `output.path`, so it is impossible to handle

**Comment by dmtkpv** [comment]
It is possible to obtain a virtual file from `compiler.outputFileSystem`
Use `before` method to register the home page route and read the generated `index.html` file

```javascript
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')

function absPath (value) {
    return path.join(__dirname, value);
}

module.exports = {

    plugins: [
        new HtmlWebpackPlugin({
            filename: '../index.html'
        })
    ],

    devServer: {
        contentBase: 'public',
        port: 49030,
        before (app, server, compiler) {
            app.get('/', (req, res) => res.send(compiler.outputFileSystem.readFileSync(absPath('public/index.html'), 'utf8')))
        }
    },

    output: {
        path: absPath('public/build'),
        publicPath: '/build/'
    }

}
```

**Comment by alexander-akait** [comment]
Again, you have invalid path, no need to do this hack and it is dirty, you should not store files above `output.path`, serve can't handle them

**Comment by GiancarlosIO** [comment]
hi @alexander-akait , is this a breaking change related to v4?
In v3 (by using historyApiFallback: true) the root '/' URL always served the index.html even if the public path was set to a value like '/static/js/.

I was trying to update to webpack 5 and just notice that now my root URL '/' is giving a 'Cannot GET /'  error when output.publicPath is set to '/static/js/. And yep, I can access to '/static/js/index.html' but that feels kind of weird. 
I would like to know if this is the expected behavior 🤔 

(There is no problem when building in prod because I can use the html-webpack-plugin filename: '../../index.html' option to generate the HTML file two folders above)

**Comment by alexander-akait** [comment]
What is `static` (i.e. previously `contentBase` value)
