### ISSUE TITLE
please open a new branch to support webpack 2

### ISSUE THREAD

**Issue by zhaxi** [webpack/webpack-dev-server#363]
Webpack 2.0 beta makes a lot of changes that current webpack-dev-server can't follow up, could you open a branch to support webpack 2.0 beta?

**Comment by stevenjlho** [comment]
+1

**Comment by ahlee2326** [comment]
+1

**Comment by mindreframer** [comment]
that is true... could we keep up the 1.x releases for some time, until the rest of the ecosystem has caught up with changes? 

For example I really need this commit: 
- https://github.com/webpack/webpack-dev-server/commit/434651fc21ddaea8f4875c1f4dd0eaea754f17d0

I'm using a framework (Phoenix / Elixir) , that starts webpack in the background and currently it just continues to run after the main application stops. I was hoping for a 1.4.2 release, but it is only available in 2.0.0-beta, which I can't use, because there is a boatload of plugins not compatible with 2.0 webpack  (at least in the package.json). Updating them all just to be able to install webpack 2.0 is unfeasible. 

Would it be possible to release some more 1.4.x versions with changes that don't break backward-compatibility? 

That would be great!

**Comment by SpaceK33z** [comment]
I'm currently working on making a 1.x release.

**Comment by SpaceK33z** [comment]
Version `1.15.0` has been released. The [changelog](https://github.com/webpack/webpack-dev-server/blob/webpack-1/CHANGELOG.md) is in the `webpack-1` branch.
