### ISSUE TITLE
Does not work hrm

### ISSUE THREAD

**Issue by Ruzaev2020** [webpack/webpack-dev-server#3792]
Hello, there is no way to do hmr for js and html. In 2020, a stream of questions on hrm flooded, I tried almost everything, works  only  `API`

Installed `webpack-dev-server ^4.1.0`, `webpack ^5.51.1`  and  `webpack-cli ^4.8.0`

> **Folder structure**

![image](https://user-images.githubusercontent.com/63113266/132085393-9a03b9d8-3cce-4cd2-9166-0c4e218e8207.png)

Point of entry `index.js`
```javascript
import './scss/main.scss';
import './js/app.js';
```

hrm works if in `index.js`  add
```javascript
if (module.hot) {
   module.hot.accept();
}
```
It works don't understand how, how to connect separate modules is not clear.
You can give detailed instructions on your  `API`

> **Here webpack.dev.js**
```javascript
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
	mode: 'development',
	context: path.resolve(__dirname, 'src', 'public'),
	entry: {
		main: {
			import: './index.js',
			filename: '[name].js'
		}
	},
	output: {
		path: path.resolve(__dirname, 'dist', 'public'),
		clean: true
	},
	devServer: {
		open: true
	},
	module: {
		rules: [
			{
				test: /\.css$/i,
				use: [MiniCssExtractPlugin.loader, 'css-loader']
			},
			{
				test: /\.s[ac]ss$/,
				use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader']
			},
			{
				test: /\.(woff|woff2|eot|ttf|otf)$/i,
				type: 'asset/resource'
			}
		]
	},
	plugins: [
		new HtmlWebpackPlugin({
			template: './index.html'
		}),
		new MiniCssExtractPlugin({
			filename: './css/[name].css'
		})
	]
};
```

**Comment by alexander-akait** [comment]
Hot module replacement is not possible for any code, if you use react I recommend to use https://github.com/pmmmwh/react-refresh-webpack-plugin, if you use vue, please use `vue-cli`, for angular ng, for custom code you need write hot reload logic for the each component of your system, it is not very easy and hard to maintenance, by default only `CSS` support HMR, because logic is simple for this, so not simple way to do it, you can read https://webpack.js.org/guides/hot-module-replacement/ and https://webpack.js.org/concepts/hot-module-replacement/ and https://webpack.js.org/api/hot-module-replacement/ if you real want to write HMR code, unfortunately I will inform you that no one will write it to you, you need knowledge to do it, feel free to feedback

**Comment by Ruzaev2020** [comment]
And in the future you will do automatic hmr?

**Comment by alexander-akait** [comment]
We can't reload any code, because code can have side effects like changing DOM, store something, set cookie and etc, each actions should rollback and apply again module code, but we can't know how to remove your cookie for example

**Comment by Ruzaev2020** [comment]
Thanks for answers!!!
