### ISSUE TITLE
querystring dependency is depreacated

### ISSUE THREAD

**Issue by jcoyne** [webpack/webpack-dev-server#3862]
Webpack-dev-server 4.2.1 depends on url 0.11.0. This package hasn't had a release in 6 years.  It in turn depends on querystring ^0.2.0.  When you install that you get the deprecation warning:

```
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
$ npx webpack-cli info

  System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 60.38 MB / 16.00 GB
  Binaries:
    Node: 16.9.1 - /usr/local/homebrew/bin/node
    Yarn: 1.22.11 - /usr/local/homebrew/bin/yarn
    npm: 7.21.1 - /usr/local/homebrew/bin/npm
  Browsers:
    Brave Browser: 80.1.4.95
    Chrome: 93.0.4577.82
    Firefox: 92.0
    Safari: 14.1.2
  Packages:
    eslint-import-resolver-webpack: ^0.13.1 => 0.13.1
    html-webpack-plugin: ^5.3.2 => 5.3.2
    webpack: ^5.52.0 => 5.53.0
    webpack-cli: ^4.8.0 => 4.8.0
    webpack-dev-server: ^4.1.1 => 4.2.1
 ```
 
### Expected Behavior

No deprecations when you install the package

### Actual Behavior

A deprecation warning for `querystring` is present.

**Comment by alexander-akait** [comment]
We need this package for legacy platform, otherwise IE will not work, we can't fix it

**Comment by jcoyne** [comment]
Even Microsoft stopped supporting IE.  https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666  What is the timeline for supporting it for webpack-dev-server?

**Comment by alexander-akait** [comment]
A lot of our developers still use IE11 (not everyone behaves like modern web), we can't drop it right now

**Comment by jensenbox** [comment]
> We just drop ie11 in the next major release and remove this package

No rush but was just wondering when the next release will be.

**Comment by rinsuki** [comment]
actually webpack-dev-server isn't using `querystring` package, but it comes from `url` package, which is providing node built-in `url` module for non-node environment (especially browser).

to remove `url` package, we need to replace `url` package function with some replacement.

in `client-src/**/*`, `url` package is used by two file.

first one is `client-src/utils/parseURL.js`. 

https://github.com/webpack/webpack-dev-server/blob/c13aa560651a3bb4c4a7b1b4363c04383596c7e9/client-src/utils/parseURL.js#L36-L39

but in this case, I think we can simply replace with `new URL` because `new URL` is used by other-case of `if`.

https://github.com/webpack/webpack-dev-server/blob/c13aa560651a3bb4c4a7b1b4363c04383596c7e9/client-src/utils/parseURL.js#L22-L30

last one is `client-src/utils/createSocketURL.js`, which uses `url` package for building URL. I don't know about replacement implementation for this.

https://github.com/webpack/webpack-dev-server/blob/c13aa560651a3bb4c4a7b1b4363c04383596c7e9/client-src/utils/createSocketURL.js#L83-L90

actually `url` package also used by `lib/*` things, but it was resolved to node-builtin module rather than npm package, so we don't need to care about `lib/*` file (if my guess is correct)
