### ISSUE TITLE
Cannot get compiler in onBeforeSetupMiddleware

### ISSUE THREAD

**Issue by ahungrynoob** [webpack/webpack-dev-server#4016]
### Bug report
![image](https://user-images.githubusercontent.com/26563778/140686184-24e92ec5-1299-4c81-8201-745d22023230.png)

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please look at source code https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L1475, use `this.compiler`
