### ISSUE TITLE
dependency: node-forge vulnerability <1.3.0

### ISSUE THREAD

**Issue by idodoroz4** [webpack/webpack-dev-server#4351]
Please update node-forge to 1.3.0

output from "npm audit" :

```
node-forge  <1.3.0
Severity: high
Improper Verification of Cryptographic Signature in node-forge - https://github.com/advisories/GHSA-cfm4-qjh2-4765
fix available via `npm audit fix`
node_modules/node-forge
```

**Comment by Changyong-Jeon** [comment]
`selfsigned` uses `node-forge@1.2.0`

https://github.com/jfromaniello/selfsigned/issues/55

**Comment by idodoroz4** [comment]
Yeah I made a mistake. Sorry.

**Comment by stevenleeg** [comment]
FYI for anybody who lands here looking for a quick fix since webpack-dev-server is still using a version of `selfsigned` that uses the affected `node-forge` package: I added the following to my `packages.json`:

```json
{
...
    "resolutions": {
        "webpack-dev-server/selfsigned/node-forge": "1.3.0"
    }
...
```

If you're reading this in the future you may not need to resort to this since I'm sure the relevant packages will end up being updated.
