### ISSUE TITLE
crashing and exiting on syntax error

### ISSUE THREAD

**Issue by Offirmo** [webpack/webpack-dev-server#463]
During development, I usually write temporary invalid code (ex. after a copy/paste). Then I stuff like that happen : 

```
.../webpack-dev-server/node_modules/webpack-dev-middleware/middleware.js:106
			if(err) throw err;
			        ^
ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' ../../user/index in ...
```

Then webpack-dev-server/ crashes : `Exit status 1` :-( And I have to manually restart it...

I searched into the config for an option to make the server more resilient, but didn't found one.

Shouldn't the request just fail and wait for further file change (nodemon like) ? Any advice ?

**Comment by pseidemann** [comment]
I think the default is not to crash. maybe you started the server with `--bail`?

**Comment by merajsahebdar** [comment]
I had this issue ... but I solved by just adding path in output options! :|

**Comment by LaurensRietveld** [comment]
I'm having this issue as well. Any luck finding a solution @Offirmo ? (adding the path to output options does not help, and `--bail` is not set)

**Comment by cgatian** [comment]
Fixed this by using an absolute path in my webpack.config

 ```
const path = require('path');
...
 output: {
        // The output directory as absolute path (required).
        path: path.resolve(__dirname, 'dist'),
```

**Comment by SpaceK33z** [comment]
Jep, absolute url like above is the way to go.

**Comment by Venryx** [comment]
Since this thread shows in search results on the topic (and I couldn't find any including the solution I eventually found), I thought I'd add the problem (and solution) for my case.

So the problem was the same as the one above, basically, in that regular compile errors were causing webpack to crash, even though `watch` was enabled, and `bail` was not enabled.

I eventually found the cause -- the following (inline) plugin was present in the project's `webpack.config.js` file:
```diff
webpackConfig.plugins = [
	// Plugin to show any webpack warnings and prevent tests from running
	function () {
		let errors = []
		this.plugin("done", function (stats) {
			if (stats.compilation.errors.length) {
				// Log each of the warnings
				stats.compilation.errors.forEach(function (error) {
					errors.push(error.message || error)
				})

				// Pretend no assets were generated. This prevents the tests from running, making it clear that there were warnings.
+				throw new Error(errors)
			}
		})
	},
```

That highlighted `throw` line was the culprit. It was included in the template project from the yoeman-generator I used to begin my app, and it lay there causing the incremental builds (after an error) to not work.

Anyway, to fix it, all I did was comment out the `throw` line -- it's only useful if you're doing test-runs anyway, which I'm not. (here is the issue I opened for it, if needed for reference: https://github.com/prescottprue/generator-react-firebase/issues/36)

Anyway, just thought I'd mention it for anyone else stumbling upon this thread while searching, for a similar problem.
