### ISSUE TITLE
*.hot-update.js 404 with webpack v5, webpack-cli v4 and webpack-dev-server v3

### ISSUE THREAD

**Issue by sushmitg** [webpack/webpack-dev-server#4736]
```
"webpack": "^5.75.0",
"webpack-cli": "^4.10.0",
"webpack-dev-server": "^3.11.0",
```

I start my express server and the app loads in the browser now I go to any source file and say add `console.log` and save the file and go back to the browser and reload the page. The app doesn't load now.

In the network tab, I get 404 for the requested js file. Also, the request has 2 paths with comma separated. I don't understand what's happening here.

![image](https://user-images.githubusercontent.com/22211683/218473848-af409aa7-67a5-4ed8-bdd7-6b94335d8cd9.png)

![image](https://user-images.githubusercontent.com/22211683/218474288-f1d79514-6d68-4ea1-9ada-ea1528e16765.png)

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please check your `publicPath`, without more infromation we can't help, please fill out the issue template and I will reopen and help you, thank you
