### ISSUE TITLE
devserver: It doesn't seem possible to completely disable watching files

### ISSUE THREAD

**Issue by andrzej-woof** [webpack/webpack-dev-server#4740]
# Bug report

**What is the current behavior?**

I've tried using all webpack configuration options that I could find to completely disable watching files by devserver, but looking at the source code it seems there are some watchers (like the one in [`NodeEnvironmentPlugin`](https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/node/NodeEnvironmentPlugin.js#L48)) that get initialized no matter what is the config passed to webpack.

My workaround (that at least for now seems to work) is:

```
const compiler = webpack(devWebpackConfig);

compiler.hooks.done.tap('serve', (stats) => {
    compiler.watching.close();
    compiler.watchFileSystem.watcher.close();
    compiler.watchFileSystem.watcher = null;
    compiler.watchMode = false;
});
```

**If the current behavior is a bug, please provide the steps to reproduce.**

config settings that I've tried were:

```
static: {
  watch: false
},
liveReload: false,
hot: false,
watch: false
```

**What is the expected behavior?**

Personally I'd expect that setting `watch: false` would just disable watching

**Other relevant information:**
webpack version:  5.71.0
Node.js version: v16.10.0
Operating System: MacOS
Additional tools:

**Comment by alexander-akait** [comment]
Why do you want to disable it? Webpack is always watch files under the hood, because the main feature is hot modules and fast refresh, your solution is not workaround, you just disable watch file system so webpack can't watch files anymore and it is a good solution

**Comment by andrzej-kodify** [comment]
As for my use case, I use `webpack-dev-server` to launch the app on a CI docker container (normally hosted as static files on a CDN) in order to execute some tests. In my particular case having the watcher has a slight impact on test execution performance.

But even disregarding the use case - setting all these that webpack exposes as valid configuration options
```
static: {
  watch: false
},
liveReload: false,
hot: false,
watch: false
```
what is the point of having an active watcher, since I've explicitly configured it not to watch files, having hot modules or live reload?

**Comment by alexander-akait** [comment]
Sorry, you need provide an example (maybe some plugin do it), because we have https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L2123

**Comment by andrzej-woof** [comment]
Hmmm, you seem to be correct - I think it's only the one in [NodeEnvironmentPlugin](https://github.com/webpack/webpack/blob/main/lib/node/NodeEnvironmentPlugin.js#L48)

**Comment by alexander-akait** [comment]
I want to close this issue, because:
```
const compiler = webpack(devWebpackConfig);

compiler.hooks.done.tap('serve', (stats) => {
    compiler.watching.close();
    compiler.watchFileSystem.watcher.close();
    compiler.watchFileSystem.watcher = null;
    compiler.watchMode = false;
});
```

is not a workaround, it is a valid solution, it is a exotic case, that is why you need do some "strange" things and you don't have an option to disable it at all (the main goal for dev-server is watching :smile:), I don't think we will change it in future, so you can use it safely
