### ISSUE TITLE
How to kill current process before starting new one

### ISSUE THREAD

**Issue by craigcosmo** [webpack/webpack-dev-server#523]
If I enter commmand `webpack-dev-server` the webpack server will obviously start. But If I type that commnad again, I got error, because an instance the server is running and it's taking the locahost port.

Is there way to config webpack dev server so that it kill whatever instance of it before it starts?

**Comment by Jack-Barry** [comment]
Running `killall node` before restarting usually does the trick for me.

**Comment by craigcosmo** [comment]
like this?

`killall node && webpack-dev-server`

**Comment by Jack-Barry** [comment]
When you're running `killall node` and there's nothing to kill, that's what it will return.  I wouldn't recommend adding it to an npm script, just run it as needed, or have a script to run it only if there are node processes running that need to be killed.

**Comment by SpaceK33z** [comment]
If you search on "find and kill process in bash" on Google you'll find a lot of answers on how to do this. [This StackOverflow](https://stackoverflow.com/questions/3510673/find-and-kill-a-process-in-one-line-using-bash-and-regex) question for example. From a quick test, `pkill -f webpack-dev-server; webpack-dev-server` works. Note the use of `;` instead of `&&`, because `pkill` will return a non-zero exit-code if it can't find any processes.
