### ISSUE TITLE
How to proxy multiple path?

### ISSUE THREAD

**Issue by mrdulin** [webpack/webpack-dev-server#647]
```js
proxy: {
            '/api/ip && /api/mobile': {
                target: nodeServerHost,
                secure: false,
                changeOrigin: true
        },
       '/api/other': {
           target: otherServer,
                secure: false,
                changeOrigin: true
        }
```

I want this. How to do that?

**Comment by SpaceK33z** [comment]
The object key is regex, so you could put in some regex. Something like `^(/api/ip|/api/mobile)` should work (not tested). Also see the http-proxy-middleware for more documentation; https://github.com/chimurai/http-proxy-middleware

Since this is a question and the template very clearly states that you should ask these on StackOverflow, I'm closing this.
