### ISSUE TITLE
webpack basic auth

### ISSUE THREAD

**Issue by khalidHussain** [webpack/webpack-dev-server#665]
hey i was wondering does `webpack-dev-server` supports `basic-auth` like we have for express?? if not then any plan on adding something like that?

**Comment by SpaceK33z** [comment]
No, this will not be added to webpack-dev-server since it is outside the scope of it. It is intended for development.

Note that you can probably add this via middleware by using the `setup` method. See [documentation](https://webpack.github.io/docs/webpack-dev-server.html) about this (ctrl + F 'setup'). webpack-dev-server also uses Express btw.

**Comment by khalidHussain** [comment]
@SpaceK33z awesome man thanks
