### ISSUE TITLE
start up webpack-dev-server show error?

### ISSUE THREAD

**Issue by sundyxfan** [webpack/webpack-dev-server#690]
2016-11-07 13:33 node[6323] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

**Comment by SpaceK33z** [comment]
This seems unrelated to webpack-dev-server. Does this also happen when using webpack? Or when using Express?

You've removed the issue template so I don't know what versions and OS you're running.

**Comment by SpaceK33z** [comment]
After some searching on that error, it is because there is a limit of files you can watch in macOS. To limit the amount of files webpack watches, add something like this:

```js
watchOptions: {
  ignored: /node_modules/
}
```

If you're using the CLI, put this in the `devServer` property in your webpack config. If you're using the Node.js API, add this as the second parameter in an object.
