### ISSUE TITLE
No HMR for subdirectory modules

### ISSUE THREAD

**Issue by koraysels** [webpack/webpack-dev-server#731]
hi i am using  
```
"webpack": "^2.2.0-rc.3",
"webpack-dev-middleware": "^1.9.0",
"webpack-hot-middleware": "^2.14.0",
```

I use it together with browserSync and  evertyhing work almost fine. If I change stuff in the entry point or
anyhting else in the top level (where the entrypoint js file is situated) everything works! Yay!

But when i change stuff in subdirectories (and import the modules accordingly) the console gives me information that the module has changed and that is has rebuilt.

for example my output in chrome console would be:
```
[HMR] bundle rebuilding
client.js:140 [HMR] bundle rebuilt in 197ms
process-update.js:27 [HMR] Checking for updates on the server...
process-update.js:100 [HMR] Updated modules:
process-update.js:102 [HMR]  - ./web/app/src/js/pages/homepage.js
process-update.js:107 [HMR] App is up to date.
```

but it did not load the changes at all... is there something I am missing or is this a known bug ?

BTW: I am not using react

**Comment by SpaceK33z** [comment]
This is not an issue in webpack-dev-server (or dev-middleware for that matter), since it doesn't handle the logic to determine if a update is necessary.

This is a not a known bug. I don't know if it's a bug in webpack/webpack or webpack-hot-middleware; you'll need to temporarily remove webpack-hot-middleware to isolate it a bit. Then make a simple repository that reproduces the problem. Without a repo, it's very unlikely somebody will take a look at it since these kind of things take too much time for us to reproduce by hand.
