### ISSUE TITLE
DefinePlugin not working with HMR, publicPath and webpack-dev-server

### ISSUE THREAD

**Issue by georgiosd** [webpack/webpack-dev-server#734]
webpack 2.2.0-rc3 with webpack-dev-server rc0, I'm seeing this:

I have a `DefinePlugin` in my list of plugins that will define `ENV` which is later compared to bootstrap angular2. 

It seems that if I build the project normally (no HMR entry, HMR plugin or `publicPath`), it will work just fine. `publicPath` is necessary because this is an electron app. 

If I enable all that, chromium will complain that ENV is not defined.

Any ideas?

**Comment by SpaceK33z** [comment]
webpack-dev-server doesn't do anything special with plugins, so it's highly unlikely that the problem is in this repository. Also I use that plugin in every project of mine and it works... You could try if the same thing happens with `webpack --watch`, webpack-dev-server essentially does that under the hood. Also, do you have some conditional configuration that might cause this issue?

**Comment by georgiosd** [comment]
Sigh... one of those things where you try again with a fresh head and it doesn't break, as if fatigue made you see errors where there were none.

I'm not seeing this today, closing for now, sorry for the inconvenience, should have waited until the morning to open the issue.
