### ISSUE TITLE
DevServer keeps reloading page with --hot [minimal repo provided]

### ISSUE THREAD

**Issue by joanasleet** [webpack/webpack-dev-server#765]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`webpack-dev-server --inline --hot` correctly identifies module change, but doesn't "hot reload" - just refreshes page

**If the current behavior is a bug, please provide the steps to reproduce.**
Please see here: https://github.com/joanasleet/webpack-hmr-test

**What is the expected behavior?**
Change modules are hot-swapped without page reload.

**Please mention your webpack and Operating System version.**
`webpack@2.2.0`
`webpack-dev-server@2.2.0`
`latest archlinux`
also tried with `node@6.9.x`

Help is greatly appreciated!

**Comment by SpaceK33z** [comment]
This is because hot reloading doesn't work automatically unfortunately. There are specific packages to make it work for e.g. React. style-loader already has HMR baked in for CSS. There are plenty of tutorials available on how to make this work.

It refreshes the page because if it can't find any function which accepts the hot reload, it falls back to a full page refresh.

Checkout the [official docs](https://webpack.js.org/concepts/hot-module-replacement/), which give some background info.

**Comment by joanasleet** [comment]
I went through quite some tutorials already. I also use `style-loader` in the given example.
I'll follow your advice then, thanks.

**Comment by SpaceK33z** [comment]
Okay, but without some handler for your React modules it will never be able to hot reload. Note that if you want to force it to NOT refresh the page, you can use `--hot-only`.

**Comment by joanasleet** [comment]
This worked: https://webpack.js.org/guides/hmr-react/
@SpaceK33z Thank you for pointing me to the right resource. There is so much noise regarding webpack on the internet.
